In [1]:
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import platform

import os, warnings # 경고메세지 라이브러리
import re   # 정규표현식
import time
warnings.filterwarnings(action='ignore') # 경고메세지 무시

import pandas as pd

In [2]:
# OS 별로 웹드라이버 로드(windows, mac)
if platform.system() == "Windows":
    driver = webdriver.Chrome('../chromedriver_90')
elif platform.system()=="Darwin":
    driver = webdriver.Chrome('../chromedriver')
else:
    print("Unknown System")
    
url = 'http://www.lotteria.com/Shop/Shop_List.asp#devCallShopList'
driver.get(url)
time.sleep(3)

In [3]:
# 마지막 페이지 이동
end_btn = driver.find_element_by_css_selector('a.go.end')
end_btn.click()
time.sleep(5)

In [4]:
# 마지막 페이지 확인
end_num = 0

while 1 : 
    now_page = int(driver.find_element_by_css_selector('span>strong').text)
    now_page

    if now_page > 10 :
        print('마지막 페이지 확인')
        page = driver.page_source
        soup = BeautifulSoup(page, 'lxml')

        end_page = soup.select_one('a.go.end')

        end_num = int(end_page.find_all_previous()[2].text)
        end_num
        break
    else :
        time.sleep(2)

마지막 페이지 확인

In [5]:
idx_list = []
code_list = []

# 1부터 마지막 페이지까지 반복
for page_num in range (1,end_num + 1):

    # 자바스크립트 이용하여 페이지 이동
    driver.execute_script(f"goPage({page_num})".format())
    
    # 현재 페이지 상태 확인 후 페이지 이동이 될 때까지 2초씩 대기 
    while 1 : 
        now_page = int(driver.find_element_by_css_selector('span>strong').text)
        now_page
        
        if now_page == page_num :
            print(f'{page_num} 확인', end='')
            break
        else :
            time.sleep(2)

    # 현재 페이지 소스 객체 생성
    page_one = driver.page_source
    soup = BeautifulSoup(page_one, 'lxml')        
    place_num = soup.find_all('td',class_='first num')

    # url 주소 안의 idx와 StoreCode 추출
    for one in place_num:
        first_one = one.a.get("onclick")[7:19][0:4]    
        second_one = one.a.get("onclick")[7:19][-5:]

        idx_list.append(first_one)
        code_list.append(second_one)
        
    print(f', {page_num} 완료')

1 확인, 1 완료
2 확인, 2 완료
3 확인, 3 완료
4 확인, 4 완료
5 확인, 5 완료
6 확인, 6 완료
7 확인, 7 완료
8 확인, 8 완료
9 확인, 9 완료
10 확인, 10 완료
11 확인, 11 완료
12 확인, 12 완료
13 확인, 13 완료
14 확인, 14 완료
15 확인, 15 완료
16 확인, 16 완료
17 확인, 17 완료
18 확인, 18 완료
19 확인, 19 완료
20 확인, 20 완료
21 확인, 21 완료
22 확인, 22 완료
23 확인, 23 완료
24 확인, 24 완료
25 확인, 25 완료
26 확인, 26 완료
27 확인, 27 완료
28 확인, 28 완료
29 확인, 29 완료
30 확인, 30 완료
31 확인, 31 완료
32 확인, 32 완료
33 확인, 33 완료
34 확인, 34 완료
35 확인, 35 완료
36 확인, 36 완료
37 확인, 37 완료
38 확인, 38 완료
39 확인, 39 완료
40 확인, 40 완료
41 확인, 41 완료
42 확인, 42 완료
43 확인, 43 완료
44 확인, 44 완료
45 확인, 45 완료
46 확인, 46 완료
47 확인, 47 완료
48 확인, 48 완료
49 확인, 49 완료
50 확인, 50 완료
51 확인, 51 완료
52 확인, 52 완료
53 확인, 53 완료
54 확인, 54 완료
55 확인, 55 완료
56 확인, 56 완료
57 확인, 57 완료
58 확인, 58 완료
59 확인, 59 완료
60 확인, 60 완료
61 확인, 61 완료
62 확인, 62 완료
63 확인, 63 완료
64 확인, 64 완료
65 확인, 65 완료
66 확인, 66 완료
67 확인, 67 완료
68 확인, 68 완료
69 확인, 69 완료
70 확인, 70 완료
71 확인, 71 완료
72 확인, 72 완료
73 확인, 73 완료
74 확인, 74 완료
75 확인, 75 완료
76 확인, 76 완료
77 확인, 77 완료
78 확인, 78 완료
79 확인, 79 완료
80 확인, 80 완료
81 확인, 81 완료
82 확인, 82 완료
83 확인, 83 완료
84 확인, 84 완료
85 확인, 85 완료
86 확인, 86 완료
87 확인, 87 완료
88 확인, 88 완료
89 확인, 89 완료
90 확인, 90 완료
91 확인, 91 완료
92 확인, 92 완료
93 확인, 93 완료
94 확인, 94 완료
95 확인, 95 완료
96 확인, 96 완료
97 확인, 97 완료
98 확인, 98 완료
99 확인, 99 완료
100 확인, 100 완료
101 확인, 101 완료
102 확인, 102 완료
103 확인, 103 완료
104 확인, 104 완료
105 확인, 105 완료
106 확인, 106 완료
107 확인, 107 완료
108 확인, 108 완료
109 확인, 109 완료
110 확인, 110 완료
111 확인, 111 완료
112 확인, 112 완료
113 확인, 113 완료
114 확인, 114 완료
115 확인, 115 완료
116 확인, 116 완료
117 확인, 117 완료
118 확인, 118 완료
119 확인, 119 완료
120 확인, 120 완료
121 확인, 121 완료
122 확인, 122 완료
123 확인, 123 완료
124 확인, 124 완료
125 확인, 125 완료
126 확인, 126 완료
127 확인, 127 완료
128 확인, 128 완료
129 확인, 129 완료
130 확인, 130 완료
131 확인, 131 완료

In [6]:
# 웹드라이버 종료
driver.close()

In [7]:
# idx_list의 길이 확인
len(idx_list)

1306

In [8]:
store_names = [] # 지점명
store_addrs = [] # 지점주소

# user-agent 정보를 넣어서 웹브라우저 정보를 변경
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36'}
    
for i in range(len(idx_list)) :
    
    # 메인 화면에 가게 이름의 url을 통해 store_page(html)정보를 담는다.
    url = f'http://www.lotteria.com/Shop/Shop_View.asp?Idx={idx_list[i]}&StoreCode={code_list[i]}'
    store_page = requests.get(url, headers=headers).content
    detail = BeautifulSoup(store_page, 'lxml')

    store_name = detail.find("h3").text
    store_names.append(store_name)
    store_addr = detail.find("td",class_='rt').span.text.strip()
    store_addrs.append(store_addr)
    
#     time.sleep(1)
    
    print(f'{i}, {store_name} : {store_addr}')

0, 가평휴게소(상) : 경기 가평군 설악면 미사리로 544
1, 아산장재 : 서울 용산구 한강대로71길 47
2, 수원파장 : 경기 수원시 장안구 파장로 91
3, 롯데더몰여수 : 전남 여수시 국포1로 36
4, 김포마산 : 경기 김포시 김포한강8로148번길 5
5, 신정네거리역 : 서울 양천구 신월로 297
6, 대구성당D/T : 대구 달서구 구마로 209
7, 진주혁신 : 경남 진주시 소호로 12
8, 영암대불 : 전남 영암군 삼호읍 대불주거로 145
9, 안산사동 : 경기 안산시 상록구 항가울로 28
10, 의정부고산 : 경기 의정부시 문충로 116
11, 용인휴게소(하) : 경기 용인시 처인구 양지면 주북로94번길 30-1
12, 진영휴게소(하) : 경남 김해시 진영읍 하계로94번길 94-4
13, 포항에비뉴 : 경북 포항시 남구 중흥로 77
14, 송도달빛공원 : 인천 연수구 송도동 29-1번지(아트센터대로 169번길 100)
15, 광명역사 : 경기 광명시 광명역로 광명역 동편 맞이방
16, 문경시청 : 경북 문경시 시청1길 5
17, 청계산입구역 : 서울 서초구 청계산로 201
18, 대전목원대 : 대전 서구 도안북로93번길 7
19, 원주봉산 : 강원 원주시 행구로 69
20, 무안 : 전남 무안군 무안읍 면성1길 129
21, 안산그랑시티자이 : 경기 안산시 상록구 해양1로 199, 그랑시티 PORT AVENUE
22, 시화거북섬 : 경기 시흥시 거북섬5길 4
23, 인천왕길역 : 인천 서구 봉화로 49
24, 홈플러스강동 : 굽은다리역 앞 홈플러스강동점 1층
25, 서천장항 : 충남 서천군 장항읍 장서로 73
26, 경기북부청사 : 경기 의정부시 장곡로 620
27, 송도랜드마크시티 : 인천 연수구 랜드마크로 68
28, 청주동남 : 충북 청주시 상당구 중고개로 141번길 13-16
29, 남양주덕소 : 경기 남양주시 와부읍 수레로 100
30, 동탄산척 : 경기 화성시 동탄순환대로 245
31, 감일 : 감일백제로 109 1층
32, 대구연경 : 대구 동구 동화천로 70길 39
33, 홈플러스월드컵 : 서울 마포구 월드컵로 240
34, DMC향동 : 경기 고양시 덕양구 꽃마을로 45
35, 김포풍무 : 경기 김포시 풍무로 122
36, 논산내동 : 충남 논산시 중앙로 255
37, 세종반곡 : 세종  한누리대로 1824
38, 남양주화도D/T : 경기 남양주시 화도읍 먹갓로28번길 77-4
39, 천안나사렛 : 충남 천안시 서북구 월봉로 79
40, 대구불로봉무 : 대구 동구 팔공로 131
41, 대구장기 : 대구 달서구 장기로 264
42, 광주주월 : 광주 남구 서문대로 753
43, 부산동아대 : 부산 사하구 낙동대로550번길 1
44, 구미선산 : 경북 구미시 선산읍 선산중앙로 68
45, 대구침산 : 대구 북구 침산로 170-1
46, 시흥은계 : 경기 시흥시 은계번영길 25
47, 원주단관 : 강원 원주시 단관길 125
48, 충주호암 : 충북 충주시 호암토성2로 상가동 지하1층 B-108호,109호
49, 천안역사 : 충남 천안시 동남구 대흥로 239
50, 안양석수 : 경기 안양시 만안구 안양로 483
51, 경기광주역 : 경기 광주시 역동로 59
52, 청주남문성안길 : 충북 청주시 상당구 성안로 51
53, 김포고촌 : 경기 김포시 고촌읍 장차로5번길 10
54, 부평역 : 인천 부평구 광장로 16
55, 오송역사 : 충북 청주시 흥덕구 오송읍 오송가락로 123
56, 고덕국제 : 경기 평택시 고덕면 고덕중앙로 218
57, 양양 : 강원 양양군 양양읍 양양로 15-1
58, 제주함덕 : 제주 제주시 조천읍 조함해안로 530
59, 광주효천 : 광주 남구 효천로 51
60, 비발디파크 : 강원 홍천군 서면 한치골길 262
61, 울산송정 : 울산 북구 화산로 109
62, 전주법원 : 전북 전주시 덕진구 만성중앙로 60
63, 동탄호수공원 : 경기 화성시 동탄면 동탄순환대로 127-19
64, 용산역사 : 서울 용산구 청파로 56-20
65, 수원당수 : 경기 수원시 권선구 당진로 20
66, 천안신당 : 충남 천안시 서북구 천안대로 1215
67, 이천송정 : 경기 이천시 증신로291번길 119-1
68, 이천 : 경기 이천시 이섭대천로1217번길 26
69, 홈플러스북수원 : 경기 수원시 장안구 경수대로 930
70, 구산역 : 서울 은평구 연서로 130
71, 평택서정 : 경기 평택시 정암로 32,1동
72, 마곡역 : 서울 강서구 마곡서로 56, 3동 1층 102호
73, 거제고현 : 경남 거제시 서문로 70
74, 광주운천 : 광주 서구 상무대로 879
75, 경남산청 : 경남 산청군 산청읍 친환경로 2693
76, 원주기업도시 : 강원 원주시 지정면 신지정로 180,롯데프라자
77, 홈플러스칠곡 : 대구 북구 동암로12길 8
78, 군포송정지구 : 경기 군포시 송부로 42
79, 세종고운 : 세종  마음안1로 137
80, 세종보람디엠시티 : 세종  한누리대로 2165
81, 진주초장 : 경남 진주시 초북로 40
82, 홍은포방 : 서울 서대문구 홍은중앙로 100
83, 세종소담 : 세종  한누리대로 2009
84, 용인동백 : 경기 용인시 기흥구 동백5로 21-11
85, 대구옥포 : 대구 달성군 옥포면 돌미상업로 6
86, 대구삼덕 : 대구 중구 동덕로 125
87, 송산새솔동 : 경기도 화성시 수노을중앙로 122
88, 홈플러스동광주 : 광주 북구 동문대로 200
89, 광주운리 : 광주 서구 풍암운리로 8
90, 진주대안 : 경남 진주시 진주대로 1077
91, 청주테크노폴리스 : 충청북도 청주시 흥덕구 송화로 172-1
92, 평택포승 : 경기 평택시 포승읍 여술2길 15
93, 롯데광복 : 부산 중구 중앙대로 롯데백화점 지하 1층
94, 대구황금네거리 : 대구 수성구 청수로 117
95, 제주공항국내선탑승 : 제주 제주시 공항로 제주공항
96, 마산로봇랜드 : 경상남도 창원시 마산합포구 구산면 로봇랜드로 1층
97, 전주에코 : 전라북도 전주시 덕진구 세병남로 롯데리아
98, 대구서성네거리 : 대구 중구 서성로 33
99, 다산진건 : 경기 남양주시 다산순환로 KB골든타워
100, 진도 : 전남 진도군 진도읍 남문길 6
101, 홈플러스간석 : 인천 남동구 경원대로 971
102, 평창진부 : 강원 평창군 진부면 진부중앙로 71
103, 홈플러스창원 : 경남 창원시 의창구 창원대로 415
104, 당진합덕 : 충남 당진시 합덕읍 합덕시장로 214-4
105, 판교D/T : 경기 성남시 분당구 동판교로 42
106, 이대 : 서울 서대문구 이화여대길 59
107, 이천마장 : 경기 이천시 마장면 오천로 67
108, 전주시청 : 전북 전주시 덕진구 기린대로 236
109, 경남의령 : 경남 의령군 의령읍 행복로 7
110, 전북대 : 전북 전주시 덕진구 명륜4길 17
111, 익산제일 : 전북 익산시 무왕로13길 13
112, 화성비봉 : 경기 화성시 비봉면 양노로 78-5
113, 제천강저 : 충북 제천시 강저로 226
114, 메가마트동래 : 부산 동래구 충렬대로  197 메가마트동래점 2F
115, 김해장유 : 경남 김해시 능동로167번길 1
116, 부천송내D/T : 경기 부천시 소사구 경인로 36
117, 롯데백인천터미널 : 인천 남구 연남로 35
118, 광주첨단 : 광주 광산구 첨단중앙로 152
119, 홈플러스광주하남 : 광주 광산구 용아로 390
120, 수원영통 : 경기 수원시 영통구 청명남로 21
121, 창원대동백화점 : 경남 창원시 성산구 원이대로 730 대동백화점
122, 구미산동 : 경북 구미시 신당1로2길 1동 1층
123, 롯데마트영통 : 경기 수원시 영통구 봉영로 1579
124, 미사역 : 경기 하남시 미사강변중앙로 218
125, 진해자은 : 경남 창원시 진해구 냉천로 164
126, 수원고색 : 경기 수원시 권선구 매송고색로691번길 18
127, 전북진안 : 진안군 진안읍 진무로 1093
128, 동탄주거단지 : 경기 화성시 동탄순환대로18길 16
129, 안성중앙대 : 경기 안성시 대덕면 대학2길 22
130, 영남대D/T : 경북 경산시 대학로 316
131, 홈플러스중계 : 서울 노원구 동일로204가길 12
132, 광교 : 경기 수원시 영통구 도청로89번길 43
133, 롯데마트중계 : 서울 노원구 노원로 330
134, 가평설악 : 경기 가평군 설악면 신천중앙로 98
135, 부산괴정 : 부산 사하구 괴정동 970-2
136, 경남대 : 경남 창원시 마산합포구 가포로 8
137, 서산해미 : 충남 서산시 해미면 남문2로 121
138, 서산테크노밸리 : 충남 서산시 성연면 성연4로 27-28
139, 하나로제주성산 : 제주 서귀포시 성산읍 일주동로 4282
140, 파주야당역 : 경기 파주시 경의로 1092
141, 밀양하남 : 경남 밀양시 하남읍 수산중앙로 93-1
142, 인천도화 : 인천 남구 숙골로 100
143, 광주퇴촌 : 경기 광주시 퇴촌면 천진암로 354
144, 여수예술랜드 : 전남 여수시 돌산읍 무술목길 142-1
145, 용인남사 : 경기도 용인시 처인구 남사면 한숲로 54 1층 104호
146, 장생포 : 울산 남구 장생포고래로 244
147, 용인송전 : 경기 용인시 처인구 이동면 경기동로687번길 22번길, 103,104호
148, 왕십리역사 : 서울 성동구 왕십리광장로 17
149, 화곡역 : 서울 강서구 화곡로 157
150, 홈플러스울산남구 : 울산 남구 수암로 148
151, 파주광탄 : 경기 파주시 광탄면 혜음로 1128-1
152, 부산서동 : 부산 금정구 서동로 159-7
153, 인천가정 : 인천 서구 염곡로498번길 18
154, 순천조례 : 전남 순천시 봉화2길 113
155, 롯데마트동래 : 부산 동래구 중앙대로 1393
156, 서충주신도시 : 충북 충주시 중앙탑면 기업도시로 222
157, 대전세이 : 대전 중구 계백로 1700
158, 밀양삼문 : 경남 밀양시 중앙로 241
159, 방배역 : 서울 서초구 방배로 96
160, 안동문화의거리 : 경북 안동시 서동문로 176
161, 경북의성 : 경북 의성군 의성읍 동서1길 26
162, 오남어람 : 경기 남양주시 오남읍 진건오남로 511
163, 전남곡성 : 전남 곡성군 곡성읍 곡성로 817
164, 해운대D/T : 부산 해운대구 해운대로 592
165, 강남일원 : 서울 강남구 양재대로55길 21
166, 금정역 : 경기 군포시 산본천로 213
167, 서면지하상가 : 부산 부산진구 가야대로 743
168, 경북신영주 : 경북 영주시 대학로12번길 4
169, 음성삼성 : 충북 음성군 삼성면 덕정로30번길 7-2
170, 여수죽림 : 전남 여수시 소라면 죽림로 3
171, 원주흥업 : 강원 원주시 흥업면 남원로 52-5
172, 동탄CGV : 경기 화성시 동탄대로 537
173, 창천 : 서울 서대문구 신촌로 15
174, 김포국제공항국내선청사4F : 서울 강서구 하늘길 112
175, 부산연지 : 부산 부산진구 새싹로 170
176, 평택세교 : 경기 평택시 세교로 5
177, 평택진위D/T : 경기 평택시 진위면 경기대로 1929
178, 청주옥산 : 충북 청주시 흥덕구 옥산면 청주역로 629
179, 춘천장학 : 강원 춘천시 동면 춘천순환로 600
180, 시흥현대시장 : 서울 금천구 독산로 독산로 128번길
181, 인천공항제2여객터미널3층 : 인천 중구 공항로 271
182, 부산광안역 : 부산 수영구 수영로 581
183, 인천공항제2여객터미널1층 : 인천공항 제2여객터미널 1층 3번게이트
184, 구리갈매 : 경기 구리시 갈매중앙로 91, 105호
185, 당진기지시 : 충남 당진시 송악읍 반촌로 기지시리 153-9
186, 포항법원 : 경북 포항시 북구 신덕로 274
187, 순천용당 : 전남 순천시 삼산로 102
188, 울산삼산D/I : 울산 남구 화합로 194
189, 구미신평D/T : 경북 구미시 구미대로 389(신평동)
190, 보라매타운 : 서울 관악구 보라매로5길 35
191, 진해남문 : 경남 창원시 진해구 남영로55번길 5
192, 시흥휴게소 : 경기 시흥시 서울외곽순환고속도로 105
193, 청량리역사 : 서울 동대문구 왕산로 왕산로 214길
194, 용인시청D/T : 경기 용인시 처인구 중부대로 1137
195, 전북장수 : 전북 장수군 장수읍 성산길 2
196, 목동킴스클럽 : 서울 양천구 목동동로 309
197, 롯데마트김포한강신도시 : 경기 김포시 김포한강2로 41
198, 부산지사 : 부산 강서구 과학산단2로 12
199, 경주보문 : 경북 경주시 보문로 465-67
200, 벌교 : 전남 보성군 벌교읍 채동선로 223-1
201, 용인백암 : 경기 용인시 처인구 백암면 백암로 186번길3
202, 울릉도 : 경북 울릉군 울릉읍 도동길 118
203, 대전도안 : 대전 서구 원도안로179번길 76-9
204, 롯데속초리조트 : 강원 속초시 대포항길 186
205, 내린천휴게소 : 강원 인제군 상남면 서울양양고속도로 117
206, 의정부낙양 : 경기 의정부시 용민로 407
207, 양주옥정 : 경기 양주시 회천남로 (목정동 M타워)
208, 롯데마트시흥배곧 : 경기 시흥시 서울대학로278번길 67
209, 울산역사 : 울산 울주군 삼남면 울산역로 177
210, 송파하비오 : 서울 송파구 송파대로 111
211, 광주하남2지구 : 광주 광산구 용아로379번길 54
212, 충북혁신도시 : 충북 음성군 맹동면 대하3길 위너스타워
213, 배곧신도시 : 경기 시흥시 배곧4로 103
214, 제주표선해변 : 제주 서귀포시 표선면 표선백사로 127
215, 하나로고양 : 경기 고양시 일산서구 대화로 362
216, 부산남산정역 : 부산 북구 만덕3로 21
217, 울산정자해변 : 울산 북구 화암길 3
218, 롯데마트서울양평 : 서울 영등포구 선유로 138
219, 부산전포 : 부산 부산진구 전포대로200번길 17
220, 해운대백병원 : 부산 해운대구 해운대로 875
221, 신부산역사 : 부산 동구 중앙대로 206
222, 양주광적 : 경기 양주시 광적면 삼일로 11
223, 천안불당 : 충남 천안시 서북구 불당10길 -
224, 울산우정 : 울산 중구 유곡로 20
225, 하나로마트광주수완 : 광주 광산구 임방울대로 261
226, 대전죽동 : 대전 유성구 죽동로279번길 16
227, 향남2신도시 : 경기 화성시 향남읍 발안로 발안양감로
228, 익산역 : 전북 익산시 익산대로 158-1
229, 백령도 : 인천 옹진군 백령면 백령로 236
230, 평내 : 경기 남양주시 경춘로1256번길 34
231, 인천서구 : 인천 서구 가정로 361
232, 전주평화 : 전북 전주시 완산구 모악로 4754
233, 아산테크노밸리 : 충남 아산시 둔포면 아산밸리중앙로 82
234, 진주상봉 : 경남 진주시 의병로 56
235, 대전산성 : 대전 중구 보문산로 45-1
236, 포항효자 : 경북 포항시 남구 효자동길 12
237, 홈플러스파주운정 : 경기 파주시 청암로 17번길 17
238, 오산세교D/T : 경기 오산시 경기대로 859
239, 순천오천 : 전남 순천시 오천6길 19
240, 안산와동 : 경기 안산시 단원구 와동로 43
241, 장한평역 : 동대문구 천호대로 401 삼성생명 1층
242, 충주용산 : 충북 충주시 남산로 73
243, 안양석수D/T : 경기 안양시 만안구 경수대로 1401
244, 양산증산 : 경남 양산시 물금읍 증산역로 153 정우프라자
245, 목감신도시 : 경기 시흥시 목감우회로114번길 롯데리아
246, 부산명지국제신도시 : 부산 강서구 명지국제6로 부산 강서구 명지국제8로 233 1
247, 중화역 : 서울 중랑구 동일로 802
248, 아산북수 : 충남 아산시 배방읍 북수로 121
249, 동탄역사 : 경기 화성시 동탄면 동탄기흥로257번가길 111
250, 수서역사 : 서울 강남구 밤고개로 99 SRT수서역사 지하1층
251, 대구금호사수 : 대구 북구 한강로4길 9
252, 경북도청 : 경북 안동시 풍천면 천년숲서로 29, 1층 116호
253, 진주신안 : 경남 진주시 진양호로 282
254, 양산물금 : 경남 양산시 물금읍 야리로 17
255, 제기역 : 서울 동대문구 왕산로 86
256, 안성휴게소(상) : 경기 안성시 원곡면 경부고속도로 372
257, 대구세천 : 대구 달성군 다사읍 세천남로 1581-6
258, 수원연무 : 경기 수원시 장안구 창룡대로 197
259, 경기대역 : 경기 수원시 영통구 대학4로 9
260, 파주적성 : 경기 파주시 적성면 마지리 46-8
261, 양재동 : 서울 서초구 동산로 22

262, 정읍상동 : 전북 정읍시 신경2길 28
263, 영등포롯데 : 서울 영등포구 경인로 846 롯데백화점 영등포점 지하1층
264, 영등포역사 : 서울 영등포구 경인로102길 13
265, 대구가창D/T : 대구 달성군 가창면 가창로 1075
266, 포일IT : 경기 의왕시 포일세거리로 10
267, 안성맞춤휴게소(상) : 경기 안성시 서운면 평택제천고속도로 41
268, 안성맞춤휴게소(하) : 경기 안성시 서운면 평택제천고속도로 40
269, 죽암휴게소(하)D/T : 충북 청주시 서원구 현도면 경부고속도로 289
270, 용인모현 : 경기 용인시 처인구 모현면 백옥대로 2387
271, 부산해운대좌동 : 부산 해운대구 좌동순환로 74
272, 평택안중D/I : 경기 평택시 안중읍 안현로서9길 5
273, 화성반월 : 경기 화성시 영통로27번길 1
274, 남성역 : 서울 동작구 사당로 200
275, 울산옥동타워 : 울산 남구 문수로 399
276, 영주가흥 : 경북 영주시 대동로31번길 2
277, 전주하가D/I : 전북 전주시 덕진구 덕진동2가 392-7
278, 용인천리 : 경기 용인시 처인구 이동면 백옥대로 641
279, 부산재송 : 부산 해운대구 재반로 86
280, 고성간성 : 강원 고성군 간성읍 간성로 59-1
281, 오창2산단 : 충북 청주시 청원구 오창읍 주성1길 5
282, 부산민락 : 부산 수영구 광안해변로 282
283, 이천하이닉스 : 경기 이천시 경충대로 2096-4
284, 파주당동 : 경기 파주시 문산읍 방촌로 1719-57
285, 현풍테크노폴리스 : 대구 달성군 유가면 테크노대로 61
286, 수지풍덕천 : 경기 용인시 수지구 풍덕천로 133
287, 의정부민락 : 경기 의정부시 천보로 44, 해동본타워 1층 102호
288, 광주백운 : 광주 남구 독립로 100-1
289, 세종종촌 : 세종  도움1로 108
290, 부산신호 : 부산 강서구 신호산단2로27번길 3
291, 전남함평 : 전남 함평군 함평읍 중앙길 21
292, 울산명촌 : 울산 북구 명촌로 45
293, 위례역 : 경기 성남시 수정구 위례광장로 25
294, 안산부곡 : 경기 안산시 상록구 부곡로 118
295, 청주내수 : 충북 청주시 청원구 내수읍 마산2길 49
296, 김천혁신도시 : 경북 김천시 혁신4로 7
297, 인덕원역 : 경기 안양시 동안구 흥안대로 527
298, 주안 : 인천 남구 주안로 지하86
299, 제주한림 : 제주 제주시 한림읍 936-7
300, 동탄커뮤니티 : 경기 화성시 동탄순환대로 685, 104호
301, 구미문성 : 경북 구미시 고아읍 들성로 213
302, 충남도청 : 충남 홍성군 홍북면 의향로 263
303, 평택청북D/T : 경기 평택시 청북면 서해로 1540
304, 보령동대 : 충남 보령시 주공로 5
305, 춘천우두 : 강원 춘천시 충열로 39
306, 대구율하중앙 : 대구 동구 안심로22길 40-5
307, 무주리조트 : 전북 무주군 설천면 만선로 185, 1층
308, 롯데마트마산양덕 : 경남 창원시 마산회원구 삼호로 80
309, 용산서계 : 서울 마포구 만리재로 150-1
310, 구월아시아드 : 인천 남구 인하로 563
311, 울산반구 : 울산 중구 염포로 21
312, 시흥하중 : 경기 시흥시 하중로 213-1
313, 세종부강 : 세종  부강면 부강로 42
314, 홈플러스송도 : 인천 연수구 송도국제대로 -
315, 인천학산 : 인천 남구 한나루로 389
316, 창원감계 : 경남 창원시 의창구 북면 동전로45번길 23
317, 전남구례 : 전남 구례군 구례읍 봉성로 70
318, 거제상문 : 경남 거제시 상동동 590-1
319, 김천모다아울렛 : 경북 김천시 아포읍 아포대로 1417, 김천모다아울렛 101동 3층
320, 인천공항A/S동편 : 인천 중구 운서동 2851
321, 서대문역 : 서울 서대문구 충정로2가 8-2
322, 인천공항1층 : 인천 중구 운서동 2851
323, 자운대 : 대전 유성구 자운로97번길 1층
324, 청주강내 : 충북 청원군 강내면 탑연리 277-2
325, 삼양사거리 : 서울 강북구 미아동 701-5
326, 롯데아울렛고양터미널 : 경기 고양시 일산동구 백석동 1242
327, 모슬포 : 제주 서귀포시 대정읍 하모리 2143-3
328, 부산송도 : 부산 서구 암남동 334-11
329, 용인휴게소(상) : 경기 용인시 처인구 고림동 89
330, 패션아일랜드대전 : 대전 동구 가오동 557
331, 대구역사 : 대구 북구 칠성동2가 302-155
332, 전주도청 : 전북 전주시 완산구 효자동2가 1239-4
333, 당진신평 : 충남 당진군 신평면 거산리 15-6
334, 일산웨스턴돔 : 경기 고양시 일산동구 장항동 855
335, 광주선운 : 광주 광산구 선암동 569
336, 평택비전 : 경기도 평택시 비전동 1012 J타워 1층
337, 고양원흥 : 경기 고양시 덕양구 도내동 957
338, 천왕역 : 서울 구로구 오류동 306-4
339, 아산용화 : 충남 아산시 용화동 1405
340, 아산신창 : 충남 아산시 배미동 240 1층
341, 외대역 : 동대문구 이문동 288-26
342, 화성화산D/T : 경기 화성시 안녕동 37-89
343, 청주지웰 : 충북 청주시 흥덕구 복대동 288-115 1층
344, 서울대입구역 : 서울 관악구 봉천동 863-1
345, 대전월평 : 대전 서구 월평동 912 1층
346, 신방화역 : 서울 강서구 방화동 B2-2 마곡SB타운 117호, 118호, 208-1호
347, 강릉주문진 : 강원 강릉시 주문진읍 주문리 323-6
348, 진주초전D/I : 경남 진주시 대신로 474
349, 서동탄역 : 경기 화성시 능동 1154-8
350, 오목천D/T : 경기 수원시 권선구 오목천동 316-1
351, 가평현리 : 경기 가평군 하면 현리 가평군 하면 현리 409-11
352, 천안통정 : 충남 천안시 동남구 신방동 1534
353, 성남도촌 : 경기 성남시 중원구 도촌동 604
354, 롯데이천아울렛 : 경기 이천시 호법면 단천리 산51-7
355, 제주외도D/T : 제주 제주시 외도2동 343-9
356, 여주가남 : 경기 여주군 가남면 태평리 110-7
357, 충남광천 : 충남 홍성군 광천읍 189-2 1층
358, 서울대 : 서울 관악구 대학동 산 56-1 서울대학교 內
359, 센텀프라자빌딩 : 부산 해운대구 우동 1078-1
360, 광주농성D/T : 광주 서구 죽봉대로 21-1
361, 김포구래 : 경기 김포시 김포한강9로 경기도 김포시 한강9로 76번길
362, 롯데아울렛동부산1층 : 부산광역시 기장군 기장해안로147 동부산롯데아울렛 A130
363, 원주반곡 : 강원 원주시 반곡동 1878-8
364, 청주율량2지구 : 충북 청주시 청원구 충청대로 174번길(주성동 343번지)
365, 청평D/T : 경기 가평군 청평면 청평리 312-9
366, 나주혁신 : 전남 나주시금천면 빛가람로 189-1
367, 안동용상D/T : 경북 안동시 용상동 1076-3 SK에너지 주유소 內
368, 전남장성 : 전남 장성군장성읍 영천로 166
369, 대구월드컵대로 : 대구 수성구 유니버시아드로 338(욱수동 121)
370, 부산학장 : 부산 사상구 학장동 574-100
371, 경북봉화 : 경북 봉화군 봉화읍 내성리 394-18
372, 롯데아울렛광명 : 경기 광명시 일직동 500 롯데아울렛광명점 5층내
373, 세종첫마을 : 세종 연기면 나성길 세종특별자치시 나성동 540번지
374, 경남하동 : 경남 하동군 하동읍 읍내리 233-22
375, 홈플러스세종 : 세종 금남면 세종로 세종특별자치시 어진동 307-3
376, 거제수월 : 경남 거제시 수월동 1120-11
377, 광주오포 : 경기 광주시 오포읍 양벌리 375-1
378, 대전용운 : 대전 동구 용운동 307-11
379, 명덕네거리 : 대구 중구 남산동 2110-8
380, 보문역 : 서울 성북구 보문동5가 3-1
381, 광주능평 : 경기 광주시 오포읍 능평리 437-9
382, 울산성안 : 울산 중구 성안로 195
383, 양평용문 : 경기 양평군 용문면 다문리 327-2
384, 부산대청 : 부산 중구 대청동3가 14-1
385, 제주아라 : 제주 제주시 아라1동 6105
386, 잠실롯데월드몰B1 : 서울 송파구 신천동 서울시 송파구 신천동 29번지 지하1층
387, 메가마트기장 : 부산 기장군 일광면 삼성리 기장대로 673
388, 경북고령 : 경북 고령군 고령읍 쾌빈리 왕륭로 116
389, 신호매실 : 경기 수원시 권선구 호매실동 호매실로104번길 24-61
390, 인천영종하늘도시 : 인천 중구 하늘중앙로195번길 하늘중앙로 195번길 14
391, 전주혁신 : 전북 전주시 완산구 안전로 154 104호
392, 인천서창 : 인천 남동구 서창동 인천광역시 남동구 서창남순환로 2
393, 제주항D/T : 제주 제주시 건입동 제주시 임항로 94,1~2층(건입동)
394, 부산망미 : 부산 수영구 연수로 278
395, 창원동읍 : 경남 창원시 의창구 동읍 용잠리 364-1
396, 천안차암 : 충남 천안시 서북구 차암동 436
397, 양산석산 : 경남 양산시 동면 석산리 1477-1
398, 천안성거 : 충남 천안시 서북구 성거읍 천흥리 427-2
399, 금곡 : 경기 남양주시 금곡동 156-40
400, 강릉포남 : 강원 강릉시 포남동 1291-5
401, 수원탑동 : 경기 수원시 권선구 757-1
402, 부산물만골역 : 부산 연제구 월드컵대로 12
403, 구미공단 : 경북 구미시 1공단로 212
404, 전남고흥 : 전남 고흥군고흥읍 여산당촌길 8
405, 진주하대 : 경남 진주시 도동로 236
406, 망원 : 서울 마포구 월드컵로 85
407, 마산진동 : 경남 창원시 마산합포구 진동면 진동리 850-1
408, 순창D/T : 전북 순창군 순창읍 교성리 394-6
409, 이천증포 : 경기 이천시 이섭대천로 1403
410, 부천도당 : 경기 부천시 원미구 도당동 58-2
411, 광주신용 : 광주 북구 첨단연신로91번길 6
412, 서원대 : 충북 청주시 흥덕구 모충동 134-27
413, 대전관저 : 대전 서구 관저동 1008
414, 고양관산 : 경기 고양시 덕양구 관산동 231-29
415, 김해내외D/I : 경남 김해시 내외중앙로 42
416, 제주삼화지구 : 제주 제주시 도련1동 1938-5
417, 대구진천역 : 대구 달서구 월배로 89
418, 논산연무 : 충남 논산시연무읍 안심로 152
419, 김포운양 : 경기 김포시 운양동 1299-1
420, 호매실DI : 경기 수원시 권선구 호매실동 52-1
421, 인천청라호수공원 : 인천 서구 솔빛로 88
422, 부산다대포 : 부산 사하구 다대로 698
423, 거제아주 : 경남 거제시 아주1로 38
424, 일산대화역 : 경기 고양시 일산서구 대화동 2203-1
425, 평택지산 : 경기 평택시 지산로 76
426, 경북풍기 : 경북 영주시 풍기읍 27-16
427, 임실 : 전북 임실군임실읍 운수로 19
428, 부산남포 : 부산 중구 비프광장로 15
429, 삼송신원 : 경기도 고양시 덕양구 신원동627번지
430, 여수웅천지구 : 전남 여수시 웅천동 예울마루로 37-16
431, 광주태전 : 경기 광주시 장지동 고불로 43-1
432, 대전한밭대 : 대전 유성구 덕명동 592-1
433, 익산배산 : 전북 익산시 모현동1가 871
434, 경남남지 : 경남 창녕군남지읍 문화길 35-4
435, 오금 : 서울 송파구 동남로 313(오금동,1층)
436, 롯데마트여천 : 전남 여수시 선원동 1268-2
437, 원주태장 : 강원 원주시 북원로 2680
438, 세곡 : 서울 강남구 세곡동 281-4
439, 롯데백잠실광장 : 서울 송파구 잠실동 40-1
440, 군자 : 서울 광진구 천호대로 548
441, 보광 : 서울 용산구 보광동 223-6
442, 당진 : 충남 당진시 당진중앙1로 108
443, 방이역 : 서울 송파구 마천로 25
444, 부천시청역 : 경기 부천시 원미구 중동 1031-2
445, 상일동 : 서울 강동구 상일로 33
446, 영천D/T : 경북 영천시 조교동 733-2
447, 완주삼례 : 전북 완주군 삼례읍 삼례리 1405-31
448, 화성조암 : 경기 화성시 우정읍 쌍봉로 76
449, 대구청구네거리 : 대구 수성구 범어동 1109
450, 담양D/I : 전남 담양군 담양읍 백동리 277-31
451, 인천불로 : 인천 서구 검단로744번1길 30
452, 서면일번가 : 부산 부산진구 서면로 46
453, 강동구청D/T : 서울 강동구 성내동 319-1
454, 순천신대 : 전남 순천시 해룡면 신대리 1979-1
455, 경남함안 : 경남남도 함안군 성내남길 7-4
456, 덕성여대 : 서울 강북구 수유동 279-84
457, 송도센트럴파크 : 인천 연수구 센트럴로 160, 130호
458, 부산토곡 : 부산 연제구 연산동 480-16
459, 후암 : 서울 용산구 후암동 27-13
460, 울산전하 : 울산 동구 전하동 동구 진성14길 77
461, 대소 : 충북 음성군 대소면 오산리 120-33
462, 서산호수공원 : 충남 서산시 예천동 1262-4
463, 부안 : 전북 부안군 부안읍 동중1리 124-2
464, 동대구역사2호 : 대구 동구 신암동 294
465, 인천검단 : 인천 서구 왕길동 639-4
466, 시흥거모 : 경기 시흥시 도일로135번길 4
467, 개봉 : 서울 구로구 고척동 52-197
468, 화성사강D/T : 경기 화성시 송산면 사강리 736-4
469, 대전관평 : 대전 유성구 관평동 840
470, 의정부시청 : 경기 의정부시 의정부2동 490
471, 성주 : 경북 성주군 성주읍 경산리 165-5
472, 망포역 : 경기 수원시 영통구 영통동 979-7
473, 봉천역 : 서울 관악구 봉천동 930-45
474, 개포 : 서울 강남구 개포동 158-12
475, 녹번 : 서울 은평구 은평로 206
476, 휘닉스파크 : 강원 평창군 봉평면 태기로 174
477, 홈플러스상봉 : 서울 중랑구 상봉동 ,
478, 온양D/T : 충남 아산시 문화로 301-6
479, 용인양지 : 경기 용인시 처인구 양지면 남평로6
480, 수원곡반정 : 경기 수원시 권선구 곡반정로 65번길 33, 102호
481, 인천동춘 : 인천 연수구 앵고개로 246번길 33
482, 화천사내 : 강원 화천군 사내면 사내로 33
483, 분당수내동 : 경기도 성남시 분당구 수내동 88-3번지
484, 대전터미널 : 대전 동구 동서대로 1689
485, 하나로부산 : 부산 북구 금곡대로 469
486, 학동역 : 서울 강남구 학동로 219 1층
487, 진주평거 : 경남 진주시 평거로5번길 12, 1
488, 하남풍산 : 경기 하남시 덕풍동로 111-10
489, 구의역 : 서울 광진구 아차산로 370
490, 문경새재 : 문경새재도립공원 관리사무소 옆
491, 인천소래포구역 : 인천 남동구 소래역로 50. 1층 101호 102호
492, 홈플러스남현 : 서울 관악구 과천대로 909
493, 인천허브D/I : 인천 중구 영종대로 283
494, 천안독립기념관 : 충남 천안시 동남구 목천읍 삼방로 95 독립기념관內
495, 만안구청 : 경기 안양시 만안구 문예로 48
496, 순천향대학D/T : 충남 아산시 신창면 온천대로 798
497, 김포사우 : 경기 김포시 사우중로 92
498, 강진 : 전남 강진군 강진읍 중앙로 88번지 금호상가1층
499, 부산신모라 : 부산 사상구 모라로 110번길 3
500, 경산진량 : 경북 경산시 진량읍 공단로 468
501, 부여아울렛 : 충남 부여군 백제문로 387
502, 천안성정 : 충남 천안시 서북구 서부대로 704
503, 하나로마트남창원 : 경남 창원시 성산구 가음로 100
504, 양주백석D/T : 경기 양주시 백석읍 양주산성로 574번길 7
505, 안동터미널 : 경북 안동시 경동로 130
506, 천안안서D/T : 충북 천안시 동남구 망향로 190
507, 홈플러스인천청라 : 인천 서구 중봉대로 587
508, 대전대동 : 대전 동구 계족로 174 (대동)
509, 마산역 : 경남 창원시 마산회원구 양덕옛2길 129(110호)
510, 부천약대 : 경기도 부천시 오정구 평천로 725
511, 답십리 : 서울 성동구 천호대로 308
512, 익산동산 : 전북 익산시 서동로130
513, 번동D/T : 번동사거리 현대주유소 위치
514, 대전대사 : 대전 중구 계룡로920번길 36
515, 용인동천 : 경기 용인시 수지구 수풍로131번길 1

516, 장흥 : 전남 장흥군 장흥읍 중앙로54-1
517, 문정로데오 : 서울 송파구 동남로 134
518, 익산영등 : 전북 익산시 영등동 약촌로 243
519, 안양호계 : 경기 안양시 동안구 경수대로 561
520, 전주중화산 : 전북 전주시 완산구 백제대로 224
521, 대전가수원 : 대전 서구 계백로 1161
522, 군산조촌D/T : 전북 군산시 조촌로 111
523, 김해아울렛식당가 : 경남 김해시 장유로 469
524, 역삼 : 서울 강남구 테헤란로 116
525, 대구대곡역 : 대구 달성군 화원읍 비슬로 2723
526, 완주봉동 : 전북 완주군 봉동읍 완주산단9로15
527, 잠실새내 : 서울 송파구 올림픽로 114
528, 부산하단 : 부산 사하구 낙동대로 457
529, 천호역 : 서울 강동구 올림픽로 654
530, 안양중앙 : 경기도 안양시 만안구 안양4동 710-57
531, 홈플러스경산 : 경북 경산시 경안로 288
532, 별내신도시 : 경기 남양주시 별내동 순화궁로 347
533, 홈플러스오산세교 : 경기 오산시 청학로 238
534, 대전가양D/T : 대전 대덕구 동서대로 1772(비래동)
535, 대전복수 : 대전 서구 복수동로 62번지 1층
536, 수원역사 : 경기 수원시 팔달구 덕영대로 924
537, 안산반월 : 경기 안산시 상록구 건건2길 6
538, 창동역 : 서울 도봉구 노해로 63길78
539, 송산휴게소 : 경기 화성시 송산면 고정리 349-26
540, 인천동양 : 인천 계양구 동양로111
541, 홈플러스합정 : 서울 마포구 양화로 45
542, 광주운암DI : 광주 북구 북문대로 177(운암동)
543, 여주375아울렛 : 경기 여주시 명품1로 22-5
544, 의정부녹양역 : 경기 의정부시 체육로298-33 CS타워 1,2층
545, 용인보라 : 경기 용인시 기흥구 한보라2로 5
546, 별내 : 경기 남양주시 별내동 별내 5로 5번길 11
547, 지행역 : 경기 동두천시 지행로 60
548, 홈플러스대구성서 : 대구 달서구 달구벌대로 1467
549, 부산감천 : 부산 사하구 감천로 27-1
550, 청주분평D/T : 충북 청주시 서원구 1순환로 991
551, 전주인후 : 전북 전주시 덕진구 안덕원로 237
552, 인천갈산 : 인천 부평구 평천로 324
553, 숭실대입구역 : 서울특별시 동작구 상도로 352
554, 수원호매실 : 경기 수원시 권선구 금곡로 106(금곡동)
555, 목포하당 : 전남 목포시 장미로 31
556, 엘리시안강촌리조트 : 강원 춘천시 남산면 북한강변길 688-79
557, 홈플러스인천숭의 : 인천 남구 석정로 51
558, 목동 : 서울 양천구 신목로 72
559, 홈플러스대구 : 대구 북구 중앙대로 543
560, 홈플러스부산가야 : 부산 진구 가야대로 506
561, 롯데마트서청주 : 충북 청주시 흥덕구 2순환로 1004
562, 안양박달D/I : 경기 안양시 만안구 박달로 432
563, 인천부개역 : 인천 부평구 경인로 1080
564, 대전카이스트 : 대전 유성구 구성동 대학로 291번지 학생회관 1층
565, 대흥역 : 서울 마포구 대흥로 79 (대흥동 동양엔파트)
566, 경주 : 경북 경주시 중앙로48번길 3
567, 홈플러스인천가좌 : 인천 서구 가정로 151번길 11
568, 울산방어 : 울산 동구 꽃바위로 266
569, 인천석바위 : 인천 남구 경원대로848
570, 롯데마트시흥 : 경기 시흥시 비둘기공원로 28(대야동)
571, 진해용원 : 경남 창원시 진해구 용원로7번길 18
572, 중랑역 : 서울 중랑구 망우로 192
573, 천안안서 : 충남 천안시 동남구 중암2길 23
574, 부산기장 : 부산 기장군 기장읍 읍내로 114
575, 서산휴게소(下) : 충남 서산시 해미면 삼송리 119
576, 속초터미널 : 강원 속초시 동해대로 3988
577, 문막휴게소 : 강원 원주시 문막읍 원문로 1234
578, 홈플러스유성 : 대전시 유성구 한밭대로 502 , 101
579, 안양관양 : 경기 안양시 동안구 관악대로291(관양동)
580, 남원도통 : 전북 남원시 큰들2길 25
581, 용인역북 : 경기 용인시 처인구 중부대로 1309
582, 정선에코리조트 : 강원 정선군 정선읍 병방치길 235
583, 동묘역 : 서울 종로구 종로 336
584, 망상 : 강원 동해시 동해대로 6270-20
585, 온양온천 : 충남 아산시 번영로 230
586, 부산거제 : 부산 연제구 아시아드대로 80
587, 강남우성사거리 : 서울 강남구 강남대로 334
588, 선릉 : 서울 강남구 테헤란로 316
589, 대전도안신도시 : 대전 유성구 도안대로 512-11
590, 대전유성 : 대전 유성구 계룡로 58
591, 홈플러스안동 : 경북 안동시 경동로 656
592, 목포대학 : 전남 무안군 청계면 승달산길 17
593, 대전정림 : 대전 서구 정림로 71 1층
594, 뚝섬유원지 : 서울 광진구 능동로7
595, 송파삼전 : 서울 송파구 백제고분로 254
596, 광교D/T : 경기 용인시 수지구 상현동 493-3
597, 구로IT : 서울 구로구 구로동 디지털로31길 20
598, 퇴계원 : 경기 남양주시 퇴계원면 퇴계원로 30
599, 홈플러스영등포 : 서울 영등포구 당산로 42 1,2층
600, 홈플러스김포 : 경기 김포시 감정동 중봉로 14
601, 부천중동 : 경기 부천시 원미구 중동로 254번길 104
602, 수락산역 : 서울 노원구 동일로 1668(상계동)
603, 롯데마트행당역 : 서울 성동구 행당동 328
604, 울산화봉 : 울산 북구 화봉로 74
605, 롯데마트수원천천 : 롯데마트 천천점 1층 롯데리아
606, 한남대 : 대전 대덕구 한남로 28
607, 한성대입구역 : 서울 성북구 동소문로 2
608, 전남대 : 광주 북구 우치로 102-1 (용봉동)
609, 청구역 : 서울 중구 다산로 168
610, 목포용해 : 전남 목포시 용당로 337, 2층
611, 동해쇄운 : 동해시 쇄운동 청운 1길 52 동방빌딩 (쇄운동 파리바게트 건너편)
612, 롯데씨네마광주수완 : 광주 광산구 장신로 98
613, 부산화명 : 부산 북구 화명신도시로 127
614, 홈플러스부산연산 : 부산 연제구 반송로 88
615, 강릉D/T : 강원 강릉시 성덕포남로 46
616, 진해중앙 : 경남 창원시 진해구 중원로 86번길 31
617, 대방역 : 서울 영등포구 영등포로 416 신길동 1,2층
618, 철원와수 : 강원 철원군 서면 와수로 186
619, 전주삼천 : 전북 전주시 완산구 삼천동1가 285-5
620, 무주 : 전북 무주군 무주읍 단천로 99
621, 괴산 : 충북 괴산군 괴산읍 괴강로 4
622, 포천운천 : 경기 포천시 영북면 운천안길 26
623, 원주단계 : 강원 원주시 천사로 63
624, 롯데마트원주 : 강원 원주시 봉화로 1
625, 동대구역사 : 대구 동구 동대구로 550
626, 포항문덕 : 경북 포항시 남구 오천읍 원동로 66
627, 홈플러스경주 : 경북 경주시 공단로 97
628, 광주양산 : 광주 북구 임방울대로 1068  (용두동)
629, 구미봉곡 : 경북 구미시 봉곡동로 4
630, 홈플러스안산 : 경기 안산시 상록구 충장로 432
631, 롯데몰김포공항 : 서울 강서구 하늘길 38
632, 대구동호D/T : 대구 동구 안심로 288
633, 신경주역사 : 경북 경주시 건천읍 신경주역로 80
634, 파주아울렛 : 경기 파주시 회동길 390  롯데프리미엄아울렛 A블럭 3층
635, 송파 : 서울 송파구 가락로 164
636, 김포양곡 : 경기 김포시 양촌읍 양곡2로 30번길 7-19
637, 중동인성 : 경기 부천시 원미구 중동 석천로 106 인성프라자1,2층
638, 오이도D/I : 경기 시흥시 정왕신길로 49번길 53
639, 중곡 : 중곡동 중마 초등학교 부근
640, 홈플러스작전 : 인천 계양구 계양대로 27
641, 울산세이브존 : 울산 남구 번영로 250번길 9
642, 롯데마트송파 : 서울 송파구 중대로 80
643, 대전와동D/T : 대전광역시 대덕구 와동 375번지
644, 충주연수 : 충북 충주시 계명대로 238
645, 망우 : 서울 중랑구 봉우재로 239
646, 인천청라 : 인천 서구 인천 서구 청라에메랄드로99
647, 롯데마트삼양 : 서울 강북구 삼양로 247
648, 영광 : 전남 영광군 영광읍신남로 185-2
649, 청양 : 충남 청양군 청양읍 중앙로 147
650, NC강서 : 서울 강서구 강서로 56길 17
651, 광주동강대 : 광주 북구 동문대로 69
652, 상계 : 서울 노원구 한글비석로 369
653, 부산미남역 : 지하철 3호선 미남역 1번 출구에서 사직동 방향 150M(TOP마트인근)
654, 일산킨텍스 : 경기 고양시 일산서구 한류월드로 407(대화동 제2킨텍스 전시장 1층)
655, 강남역 : 강남역 9번이나 10번출구 뉴욕제과 뒷건물
656, 대구스타디움 : 대구 수성구 유니버시아드로 140
657, 부산명지 : 부산 강서구 명지오션시티11로 74
658, 방학 : 방학 4거리에서 우이동 방면으로 -신동아 아파트 전
659, 시흥월곶 : 경기 시흥시 월곶동 월곶중앙로(61) 월곶동
660, 상암 : 서울 마포구 월드컵북로 402 KGIT센터 150~152호
661, 광양마동 : 전남 광양시 사동로 179  (마동)
662, 강일 : 서울 강동구 아리수로93길 33-9
663, 발산역 : 서울 강서구 강서로 56길 24
664, 문막 : 강원 원주시 문막읍 원문로 1587
665, 목동행복한백화점 : 서울 양천구 목동동로 목동동로309
666, 종암 : 서울 성북구 종암로 91
667, 마산내서 : 경남 창원시 마산회원구 내서읍 경남대로 915
668, 청주터미널 : 충북 청주시 흥덕구 가경동 1449번지 터미날타워 10호동
669, 천안상록리조트 : 충남 천안시 동남구 수신면 수신로 576
670, 광명하안 : 경기 광명시 범안로 1045
671, 광혜원 : 광혜원시외버스정류장 맞은편
672, 부평 : 인천 부평구 경원대로 1399
673, 시흥정왕역 : 경기 시흥시 마유로418번 길10
674, 운정한빛 : 경기 파주시 와석순환로 125 (동패동)
675, 여의도선착장 : 서울 영등포구 여의동로 290
676, 청주하나로 : 충북 청주시 상당구 무농정로 32 청주하나로클럽內
677, 전주효자서부 : 전북 전주시 완산구 호암로 65
678, 성수역 : 성수역1번출구 150m
679, 아산탕정 : 충남 아산신 탕정면 탕정면로 37
680, 구파발역 : 서울시 은평구 진관동 지하철 3호선구파발역 1번출구앞 구파발역복합환승센터1층
681, 부천범박 : 경기 부천시 소사구 소사동로 87
682, 남양주진접 : 경기 남양주시 진접읍 해밀예당 3로 51
683, 고양 : 경기도 고양시 덕양구 고양동 682번지 sun빌딩 1층
684, 일산가좌 : 경기 고양시 일산서구 가좌1로53
685, 롯데몰이시아폴리스점 : 대구 동구 팔공로49길 16
686, 키즈마트부산 : 부산 진구 신천대로 241
687, 군산수송 : 전북 군산시 서수송 1길  2
688, 암사역 : 서울 강동구 올림픽로792
689, 김포통진 : 경기 김포시 통진읍 김포대로 2242
690, 상봉역 : 서울시 중랑구 상봉동 115-14 1층
691, 구리돌다리 : 경기 구리시 검배로 21
692, 구리인창 : 경기 구리시 동구릉로 108
693, 안성공도D/T : 경기 안성시 공도읍 서동대로 3904-6
694, 일산식사 : 경기 고양시 일산동구 위시티2로 11번길 45
695, 충북오송 : 충북 청원군 오송읍 오송생명로 194
696, 울산남목 : 울산 동구 방어진순환도로 1133, 102호
697, 정릉 : 서울 성북구 보국문로8길 4, 1층(정릉동)
698, 인제터미널 : 강원 인제군 인제읍 비봉로 43길
699, 용인흥덕 : 경기 용인시 기흥구 흥덕2로 87번길 18
700, 포천송우 : 경기 포천시 소흘읍 송우로 53
701, 완도 : 전남 완도군 완도읍 군내리장보고대로 210
702, 전주송천 : 전북 전주시 덕진구 솔내로 182 (송천동2가)
703, 주안D/T : 도화 IC출구 맞은 편 SK주유소 삼성A/S센터 사이에 위치하고 있음.
704, 용인죽전1동 : 용인시 수지구 죽전동 1190-1 거풍프라자 1층
705, 방화 : 서울 강서구 양천로 73
706, 성남테크노밸리 : 경기 성남시 중원구 사기막골로 124
707, 중앙대 : 서울시 동작구 흑석동 182-7 1층 롯데리아
708, 장호원 : 경기 이천시 장호원읍 장감로80
709, 이수역 : 서울 동작구 동작대로 129, 지상1층
710, 수원정자 : 홈배달 가능합니디.
711, 창원소답 : 경남 창원시 의창구 읍성로 79번길2 102~104호 (소답동)
712, 공항신도시 : 인천 중구 흰바위로59번길 31
713, 부산범어사역 : 부산 금정구 중앙대로 2103
714, 용산역사ST : 서울 용산구 한강대로23길 55
715, 홈플러스김해 : 경남 김해시 김해대로 2078
716, 롯데마트제천 : 충북 제천시 용두대로 111 롯데마트제천점 내
717, 광주수완 : 수완지구 신한은행 옆
718, 군산산북 : 전북 군산시 공단대로 566
719, 길음뉴타운점 : 서울 성북구 길음로7길 6
720, 단양 : 별곡리 331번지
721, 수영로타리 : 부산시 수영구 광안동 50-13
722, 역곡역 : 경기 부천시 원미구 부일로 727
723, 대전시청 : 대전 서구 문정로 70 제이엔에스빌딩 1층
724, 용인신봉 : 경기 용인시 수지구 수지로 217
725, 구리토평 : 경기 구리시 체육관로26
726, 홈플러스밀양 : 경남 밀양시 점필재로 45 (내이동)
727, 시흥능곡 : 경기 시흥시 장현능곡로 198 (능곡동,126,127호)
728, 목포석현 : 전남 목포시 영산로 559
729, 문산 : 경기 파주시 문산읍 문향로 70
730, 함양 : 경남 함양군 함양읍 고운로 52
731, 삼호한마음 : 전남 영암군 삼호읍 신항로 63-2
732, 파주운정 : 경기 파주시 미래로 622
733, 광주두암 : 광주 북구 갈마로 53
734, 화천 : 강원 화천군 화천읍 중앙 16
735, 천안목천 : 충남 천안시 동남구 목천읍 충절로 895
736, 충남대 : 대전 유성구 궁동로 18번길-6
737, 메가마트언양 : 울산 울주군 삼남면 반구대로 612
738, 평택송탄 : 경기도 평택시 서정동 814-7번지 덕수빌딩 1층
739, 양주고읍 : 경기도 양주시 광사동 651번지 해동월드타워 1층 110호
740, 대구동성로 : 대구 중구 동성로 39
741, 공릉역 : 서울 노원구 동일로 192길 27
742, 여수여서 : 전남 여수시 여서로 164-1  (여서동)
743, 가든파이브 : 서울 송파구 충민로66
744, 진주산업대 : 경남 진주시 동진로 23(칠암동)
745, 천안아산역사 : 충남 아산시 배방읍 희망로 100
746, 홈플러스월곡 : 서울 성북구 화랑로 76
747, 안성공도 : 경기 안성시 공도읍 공도로 132
748, 창원상남 : 경남 창원시 성산구 단정로 7
749, 하나로마트울산 : 울산 울주군 범서읍 장검길10
750, 통영죽림 : 경남 통영시 광도면 죽림1로 17-51
751, 의왕오전 : 경기 의왕시 모락로26
752, 부산반송 : 부산 해운대구 아랫반송로 28-1
753, 익산모현 : 전북 익산시 고현로 90 (모현동1가)
754, 대전배재 : 대전 서구 배재로 176
755, 부천오정 : 경기 부천시 오정구 오정로249
756, 부산대 : 부산 금정구 부산대학로 47
757, 의정부신곡 : 경기 의정부시 신곡1동 동일로 462
758, 남악 : 전남 무안군 대죽동로 40
759, 부산동래역 : 부산 동래구 중앙대로 1319
760, 화성센트럴파크 : 경기 화성시 동탄지성로 116
761, 울산온양 : 울산 을주군 온양읍 온양로 95
762, 광주풍암 : 광주 서구 풍암2로 10
763, 키자니아 : 잠실 어린이 직업체험테마파트 키자니아 내 2층
764, 인천검암 : 인천 서구 승학로 505
765, 청주봉명 : 충북 청주시 흥덕구 백봉로227 이화빌딩 105호
766, 롯데마트춘천 : 강원 춘천시 방송길 84 롯데마트內
767, 사당 : 서울 서초구 동작대로 24
768, 오류동역 : 서울 구로구 경인로20길 1
769, 의왕부곡 : 경기 의왕시 부곡중앙남1길 3
770, 일산풍동 : 백마역
771, 화순 : 전남 화순군 화순읍 만연리 223
772, 건대역 : 서울 광진구 능동로 110
773, 대구수성구청 : 대구 수성구 달구벌대로 2472

774, 부산정관 : 부산 기장군 정관면 정관로 560
775, 사가정역 : 서울 중랑구 면목로 333
776, 광주동림 : 광주 광역시 서구 동천동626
777, 용인둔전 : 경기 용인시 포곡읍 포곡로 107번길 2
778, 인천간석 : 인천 남구 주안로219
779, 일산후곡 : 경기 고양시 일산서구 일산로 544
780, 인천월미마이랜드 : 인천 중구 월미문화로 81
781, 성남단대 : 경기 성남시 중원구 산성대로 372번길 15
782, 고덕역 : 서울 강동구 동남로73길 26 02호
783, 목포 : 전남 목포시 영산로 59번길 30
784, 의정부호원 : 경기 의정부시 평화로238
785, 목포북항 : 전남 목포시 청호로 173
786, 미아삼거리 : 서울 성북구 도봉로 29
787, 인천남동공단 : 인천 남동구 논현로 40 1층
788, 롯데마트광주수완 : 광주 광산구 장신로 98
789, 부천뉴코아 : 경기 부천시 원미구 송내대로 239(상동)
790, 영등포타임스퀘어B2 : 서울 영등포구 영중로 15(영등포동 4가)B2층
791, 김해율하 : 경남 김해시 장유동 율하3로 42
792, 대구서부정류장 : 대구 달서구 구마로 260
793, 신도림역 : 서울 구로구 경인로661(신도림동)
794, 대구서재 : 대구 달성군 다사읍 서재본길 4-1
795, 롯데마트서산 : 충남 서산시 충의로 27 롯데마트 2층
796, 진주금산 : 경남 진주시 금산면 금산순환로 4
797, 알펜시아리조트 : 강원 평창군 대관령면 솔봉로 325
798, 김포장기 : 경기 김포시 김포한강 1로 78번길 5(장기동)
799, 광주학동 : 광주 동구 남문로 682 (학동)
800, 전주동산 : 전북 전주시 덕진구 편운로 6
801, 평촌귀인 : 경기 안양시 동안구 평촌대로 139
802, 고양행신역 : 경기 고양시 덕양구 행신동 무원로6번길 50
803, 인천올리브 : 인천 남동구 남동대로 880
804, 롯데마트고양 : 경기 고양시 덕양구 행신동 중앙동 558번길 21
805, 양산부산대 : 경남 양산시 물금읍 삽량로 36
806, 대구사월역 : 대구 수성구 달구벌대로 3280
807, 롯데마트통영 : 경남 통영시 무전대로 65
808, 롯데마트평택배미 : 경기 평택시 평택5로 30 (합정동, 1층)
809, 여수디오션리조트 : 전남 여수시 소호동 923 디오션호텔
810, 대구아양교 : 대구 동구 아양로 240
811, 인천송도 : 인천 연수구 신송로 122
812, 대구스파밸리 : 대구 달성군 가창면 가창로 891
813, 신곡시장 : 서울 양천구 신월로 164
814, 홈플러스일산 : 경기 고양시 일산동구 중앙로1275번길 64
815, 평택팽성 : 경기 평택시 팽성읍 동서촌로97
816, 용인보정 : 경기 용인시 기흥구 죽전로 39
817, 화성향남 : 경기 화성시 향남읍 발안로 107
818, 아울렛광명 : 경기 광명시 철산로 4 지하 2층
819, 홈플러스계림 : 광주 동구 무등로 314
820, 롯데김해아울렛 : 경남 김해시 신문동72-19
821, 아산둔포 : 충남 아산시 둔포면 둔포 중앙로 148
822, 숙대입구역 : 서울 용산구 한강대로 283
823, 인천논현 : 인천 남동구 논고개로123번길17
824, 포천D/T : 경기 포천시 소흘읍 호국호 231
825, 홈플러스부산감만 : 부산 남구 우암로 124
826, 롯데마트전주송천 : 전북 전주시 덕진구 송천중앙로 82  (송천동1가)
827, 부산경성대 : 부산 남구 수영로 300
828, 롯데마트전주 : 전북 전주시 완산구 우전로 240
829, 롯데마트당진 : 충남 당진시 정안로 20 롯데마트 1층
830, 홈플러스평촌 : 경기 안양시 동안구 평촌대로 253번길 48
831, 동대문광장 : 서울 종로구 종로 286
832, 태백 : 강원 태백시 태백로 898
833, 구미양포 : 경북 구미시 옥계북로 7
834, 홈플러스오창 : 충북 청원군 오창읍 중심상업1로 8-11
835, 송악 : 충남 당진시 송악읍 신복운로 7길 4-4
836, 장승포 : 경남 거제시 능포로 132-1
837, 수원북문 : 경기 수원시 장안구 영화동 301-6
838, 홈플러스천안 : 충남 천안시 동남구 천안대로 574 홈플러스內
839, 화성봉담 : 경기도 화성시 봉담읍 동화리 599-2번지 이원타워 1층 롯데리아
840, 동해 : 강원 동해시 천곡로 74
841, 성신여대 : 서울 성북구 동소문로 117
842, 홈플러스진해 : 경남 창원시 진해구 충장로 356
843, 충주터미널 : 충북 충주시 봉계1길 49 공용터미널1층
844, 홈플러스조치원 : 세종 조치원읍 허만석로 60-1
845, 수원성대 : 경기 수원시 장안구 서부로 2121
846, 광주치평점 : 광주 서구 상무중앙로 95
847, 영덕 : 경북 영덕군 영덕읍 남석길 74
848, 칠곡석적 : 경북 칠곡군 석적읍 북중리3길 40
849, 홈플러스상인 : 대구 달서구 월배로 183
850, 홈플러스계산 : 인천 계양구 오조산 공원로 14
851, 홈플러스목포B1 : 전남 목포시 영산로 313
852, 화성동탄 : 경기 화성시 동탄문화센터로 71-3
853, 구미상모 : 경북 구미시 상사동로 64
854, 롯데마인천삼산B1 : 인천 부평구 길주로623-0
855, 용인상현 : 경기 용인시 수지구 상현로 114, 나래빌딩 104-106호
856, 원통 : 강원 인제군 북면 원통로147 길 27
857, 평촌주공공이 : 경기 안양시 동안구 관평로 170번길 33
858, 롯데마트대덕테크노밸리 : 대전 유성구 테크노 중앙로 14
859, 인천가좌 : 인천 서구 원적로 85
860, 동대문역사문화공원역 : 서울 중구 을지로 255
861, 전주터미널 : 전북 전주시 덕진구 전북 전주시 덕진구 가리내로 21
862, 청주산남 : 충북 청주시 흥덕구 산남로 70번길 3
863, 신당역 : 서울 중구 퇴계로428-1
864, 홈플러스전주 : 전북 전주시 덕진구 백제대로 771  (우아동3가)
865, 신림역 : 2호선 신림역 3, 4번 출구(신림역 4거리)
866, 원광대 : 전북 익산시 동서로 19길 103-1 (신동)
867, 천안직산 : 충남 천안시 서북구 봉주로38
868, 홈플러스해운대 : 부산 해운대구 해운대해변로 140
869, 청량리 : 청량리역3번출구 (민자역사 맞은편)
870, 울산구영 : 울산 울주군 범서읍 점촌3길 10-10 1
871, 화성기안 : 경기 화성시 효행로287.보보스프라자106
872, 대전가오 : 대전 동구 은어송로60 103호
873, 부천역 : 경기 부천시 소사구 부천로1 부천역사 쇼핑몰
874, 부천역EXP : 경기 부천시 소사구 부천로1 137호 부천역사쇼핑몰
875, 광명 : 경기 광명시 광명로 890
876, 부산사상 : 부산 사상구 사상로 211
877, 노량진 : 서울 동작구 장승배기로 171
878, 순천풍덕 : 전남 순천시 팔마로 222
879, 용인구성 : 경기 용인시 기흥구 구성로 58
880, 인천만수 : 인천 남동구 만수로47 만수메디칼 빌딩105호
881, 대전전민 : 대전 유성구 유성대로 1746-1
882, 홈플러스울산북구 : 울산 북구 신답로 26
883, 호평 : 경기 남양주시 늘을2로 14번길 3
884, 의정부제일 : 경기 의정부시 시민로131번길 16
885, 고창 : 전북 고창군 고창읍 중앙로 229
886, 홈플러스천안신방 : 충남 천안시 동남구 신촌1길23
887, 건대스타시티 : 서울 광진구 아차산로272
888, 롯데마트군산 : 전북 군산시 수송로 210-1
889, 파주교하 : 경기 파주시 책향기로 419 (동패동)
890, 인천석남 : 인천 서구 거북로 87, 1층
891, 광주문흥 : 광주 북구 서하로 384
892, 홈플러스방학 : 서울 도봉구 도봉로 678
893, 조치원 : 세종 조치원읍 조치원로 27-1
894, 롯데마트장유 : 경남 김해시 장유면 번화1로 56번길 15
895, 아산배방 : 충청남도 아산시 배방읍 공수리 149-8번지 장호빌딩1층
896, 신촌로터리 : 서울 마포구 서강로 137
897, 광주신창 : 광주 광산구 신창로 116(신창동)
898, 전주고사 : 전북 전주시 완산구 전주객사5길 22-3(고사동)
899, 오산원동 : 경기 오산시 원동로37번길 37
900, 홈플러스신내 : 서울 중랑구 신내로 201
901, 의정부회룡역 : 회룡역 1번출구 좌측 150M 위치
902, 오창 : 충북 청원군 오창읍 중심상업로 7
903, 대전반석 : 대전 유성구 반석로 9
904, 가평 : 경기 가평군 가평읍 가화로 106
905, 대산 : 충남 서산시 대산읍 구진로 20
906, 진건 : 진건초등학교 맞은편
907, 부산역 : 부산 동구 중앙대로 201(초량동)
908, 마산터미널 : 경남 창원시 마산회원구 3·15대로 756
909, 수원팔달 : 경기도 수원시 팔달구 팔달로3가 101-2
910, 곤지암 : 경기 광주시 곤지암읍 곤지암로 54
911, 홈플러스내당 : 대구 서구 달구벌대로 1821
912, 롯데마트천안성정 : 충남 천안시 서북구 성정두정로 1  1층 롯데리아
913, 홈플러스마산양덕 : 경남 창원시 마산회원구 삼호로 56
914, 캐슬플라자 : 서울 송파구 올림픽로 269 캐슬골드 B1
915, 분당미금아울렛 : 경기 성남시 분당구 미금일로154번길 20
916, 의정부가능역점 : 경기 의정부시 평화로635
917, 홈플러스강서 : 서울 강서구 화곡로 398
918, 서천 : 충남 서천군 서천읍 서천로 30
919, 홈플러스인하 : 인천 남구 소성로 6
920, 인천원당 : 인천 서구 당하동 원당대로876
921, 대림역 : 서울 영등포구 도림로 148
922, 화성태안 : 경기 화성시 병점1로 221
923, 롯데마트웅상 : 경남 양산시 삼호1길 34
924, 원주무실 : 강원 원주시 시청로 86
925, 영월 : 강원 영월군 영월읍 중앙로 24
926, 김해북부 : 경남 김해시 가야로 183
927, 인천당하 : 인천 서구 완정로 18
928, 전주메가월드 : 전북 전주시 덕진구 동부대로 1229
929, 대구칠곡매천 : 대구 북구 학정로 40
930, 청도 : 경북 청도군 청도읍 청화로 207
931, 김천EXP : 경북 김천시 시청로 66
932, 성남상대원 : 경기 성남시 중원구 희망로 348
933, 일산대화 : 경기 고양시 일산서구 대화로136
934, 음성 : 충북 음성군 음성읍 수정로 53
935, 화성발안 : 경기 화성시 향남읍 삼천병마로 207
936, 롯데마트서대전 : 대전 유성구 유성대로 26-37롯데마트(서대전점) 2층 롯데리아
937, 롯데마트의왕 : 경기 의왕시 계원대학로 7
938, 롯데마트첨단 : 광주 광산구 첨단 강변로99번길22(쌍암동)
939, 제천청전 : 충북 제천시 청전동 청전대로169
940, 안양비산 : 경기 안양시 동안구 관악대로 131
941, NC청주 : 충북 청주시 흥덕구 2순환로 1233(가경동)
942, 홈플러스시화 : 경기 시흥시 희망공원로 269
943, 일산중산 : 경기 고양시 일산동구 중산로 245번길
944, 횡성 : 강원 횡성군 횡성읍 문정로 25
945, 예천 : 경북 예천군 예천읍 중앙로 27
946, 대전역사 : 대전 동구 중앙로 215(정동)
947, 롯데마트사하 : 부산 사하구 을숙도대로 610
948, 롯데마트오산 : 경기 오산시 경기대로 271
949, 롯데마트주엽 : 경기 고양시 일산서구 중앙로1496
950, 롯데마트충주 : 충북 충주시 봉계1길 49 롯데마트2층
951, 금강휴게소 : 충북 옥천군 동이면 금갈로 596
952, 광주송정 : 광주 광산구 송정로 1번길88
953, 구미진평 : 경북 구미시 인동36길 5
954, 대구동서변 : 대구 북구 호국로 219
955, 구미원평 : 경북 구미시 구미중앙로17길 9
956, 순천시청 : 전남 순천시 장명로22(장천동)
957, 서울역광장 : 서울 용산구 한강대로 405 101호
958, 서울역사 : 서울 용산구 한강대로 405 109호 2층
959, 구미도량 : 경북 구미시 송동로 65
960, 양구 : 강원 양구군 양구읍 양록길 99
961, A.G선수촌 : 부산 해운대구 선수촌로 109-1
962, 홈플러스금천 : 서울 금천구 시흥대로 391
963, 군산대학 : 전북 군산시 황룡로 3
964, 파주법원 : 경기 파주시 법원읍 술이홀로879번길 13-2
965, 수원율현 : 경기 수원시 팔달구 일월로22번길 4
966, 천안두정 : 두정역에서 100M, 주공8단지 정문 건너편에 위치
967, 부산대연 : 부산 남구 수영로 200
968, 안산역사 : 경기 안산시 단원구 중앙대로 462
969, 시흥제일 : 경기 시흥시 호현로10번길 17
970, 강릉교동 : 강원 강릉시 교동광장로 106
971, 양산중부 : 경남 양산시 양산역로 69
972, 군포당동 : 경기 군포시 고산로262번길 1층
973, 경남합천 : 경남 합천군 합천읍 동서로 85-1
974, 제주공항 : 제주 제주시 공항로 2 국내선 청사 4층
975, 포항죽도 : 경북 포항시 북구 중흥로 187
976, 홈플러스아시아드 : 부산 연제구 종합운동장로 7 (거제동)
977, 안산제일 : 경기 안산시 단원구 선부광장1로 56
978, 대천광장 : 충남 보령시 해수욕장2길 1(신흑동)
979, 대구칠곡구암 : 대구 북구 학정로 440
980, 포항두호 : 경북 포항시 북구 두호로 26
981, 대구퀸스로드 : 대구 서구 평리로35길 18-8
982, 분당미금 : 경기 성남시 분당구 돌마로 68
983, 마산호계 : 경남 창원시 마산회원구 내서읍 호원로 220
984, 인천연희D/T : 인천 서구 서곶로 289
985, 안성중앙 : 경기 안성시 중앙로 397
986, 종각역 : 서울 종로2가 종로 68
987, 수원역광장 : 경기 수원시 팔달구 덕영대로 924
988, 목포상동 : 전남 목포시 백년대로 339
989, 부천상동 : 경기 부천시 원미구 상동로 87 가나베스트타운 110,111
990, 서울랜드2호 : 경기 과천시 막계동 광명로 181(서울랜드)
991, 울산화정 : 울산 동구 대학길 65
992, GS천안 : 충남 천안시 동남구 충절로 148번지 GS슈퍼內
993, 봉일천 : 경기 파주시 조리읍 봉천로 40
994, 시흥연성 : 경기 시흥시 진말로 19번길 16
995, 응암오거리 : 서울 은평구 응암로 177
996, 대구다사 : 죽곡 우리은행 옆 건물
997, 경상대학 : 경남 진주시 진주대로 594(가좌동)
998, 광주용봉 : 광주 북구 비엔날레로 112
999, 부산주례역 : 주례역 1번출구 100m
1000, 대구방촌 : 대구 동구 화랑로 409
1001, 대전비래 : 대전 대덕구 비래동로 13
1002, 야탑역 : 야탑역4번출구 야탑광장 맞은편 1분거리
1003, 청주금천 : 충북 청주시 상당구 수영로 285
1004, 동인천역전 : 인천 중구 참외전로 122(인현동)
1005, 울산호계 : 울산 북구 호계로 302
1006, 대전신성 : 대전시 유성구 신성남로 45(신성동)
1007, 안산신도시 : 경기 안산시 단원구 고잔동 광덕대로 154 로데오타운 1F
1008, 경주안강 : 경북 경주시 안강읍 비화원로 77
1009, 장안사거리 : 서울 동대문구 답십리로 287
1010, 대전가장 : 대전 서구 가장로106(롯데리아)
1011, 대구논공 : 대구 달성군 논공읍 논공로 741
1012, 대구나이스수성 : 대구 수성구 수성로 227
1013, 안동옥동 : 경북 안동시 경북대로 418
1014, 대구안지랑 : 대구 남구 대명로 160-2
1015, 양평 : 경기 양평군 양평읍 역전길3
1016, 창원팔용 : 창원시 의창구 팔룡동 77-1번지
1017, 여수신기 : 전남 여수시 선소로 84  (신기동)
1018, 경남창녕 : 경남 창녕군 창녕읍 명덕로 70
1019, 시흥시화 : 경기 시흥시 옥구상가2길 4
1020, 인천청천 : 대우자동차 서문 위  영아다방 사거리 효성동 방면
1021, 혜화 : 서울 종로구 창경궁로 273
1022, 금왕 : 충북 음성군 금왕읍 무극로 250
1023, 염창 : 서울 강서구 양천로 657
1024, 구미오태D/T : 경북 구미시 금오대로 292
1025, 안산초지 : 경기 안산시 단원구 광덕1로 55
1026, 울산온산 : 울산 울주군 온산읍 덕신리 270-8
1027, 울산태화 : 울산 중구 태화로 174
1028, 광주금호 : 광주 서구 금화로 89  (금호동)
1029, 의정부용현 : 경기 의정부시 충의로 62
1030, 단구GS마트 : 강원 원주시 서원대로390
1031, 안양역사 : 경기 안양시 만안구 만안로 232

1032, 홈플러스센텀시티 : 부산 해운대구 센텀동로 1-224
1033, 부산안락 : 부산 동래구 안락로 134
1034, 남양주청학 : 경기 남양주시 청학로중앙길15
1035, 동암남부 : 동암남로 5
1036, 포항흥해 : 경북 포항시 북구 흥해읍 흥해로 38
1037, 창원도계 : 경남 창원시 의창구 도계로 99
1038, 일산탄현 : 경기 고양시 일산서구 일현로 47
1039, 홈플러스동수원 : 경기 수원시 팔달구 호원로 257
1040, 광양 : 전남 광양시 광양읍 매천로835
1041, 명지대학 : 서울시 서대문구 남가좌2동 324-31
1042, 개봉역 : 서울 구로 경인로 40길 47 1F
1043, 롯데마트울산 : 울산 남구 달동 삼산로 74(달동)
1044, 양산덕계 : 경남 양산시 덕계로 78
1045, 삼천포벌리 : 경남 사천시 주공로 9
1046, 광주하남 : 광주광역시 광산구 월곡1동 538-2
1047, 인천강화 : 인천 강화군 강화읍 강화대로 419
1048, 광주진월 : 광주 남구 서문대로 662
1049, 궁전라벤더 : 대구 동구 아양로 52
1050, 익산부송 : 전북 익산시 부송로66
1051, 전주아중 : 전북 전주시 덕진구 무삼지로 66
1052, 울진D/I : 경북 울진군 울진읍 읍내리 47
1053, 대전중촌 : 대전 중구 목중로 22 1층 롯데리
1054, 장현 : 경기 남양주시 진접읍 장현로 93
1055, 인천용현 : 인천 남구 낙섬중로 42
1056, 금촌로터리 : 경기 파주시 황골로 39
1057, 남부터미널 : 서울 서초구 효령로 289 장곡빌딩 103호
1058, 하남신장 : 경기 하남시 대청로73
1059, 홈플러스울산 : 울산 중구 번영로 475
1060, 킴스순천 : 전남 순천시 비봉2길 4-12
1061, 화성남양 : 화성시 남양동 남양사거리 안쪽 아이리스프라자 1층
1062, 안산본오 : 경기 안산시 상록구 샘골로 150 동성빌딩 101
1063, 인천작전 : 인천 계양구 안남로 548
1064, 천안쌍용 : 충남 천안시 동남구 쌍용대로 84
1065, 수원터미널 : 경기 수원시 권선구 경수대로 270 1311호
1066, 부산아쿠아리움 : 부산 해운대구 해운대 해변로 266
1067, 석관 : 서울 성북구 돌곶이로 75
1068, 신김포공항 : 서울 강서구 하늘길 김포공
1069, 홈플러스구월 : 인천 남동구 에술로 198 (구월동)
1070, 청주하복대 : 충북 청주시 흥덕구 진재로 56
1071, 인천학익 : 인천 남구 매소홀로 466
1072, 시흥중앙 : 서울 금천구 금하로 712
1073, 부산터미날1호 : 부산 금정구 중앙대로 2238
1074, 청주대학 : 충북 청주시 상당구 상당로 255
1075, 원주하나로 : 단계동 원예하나로 클럽내 롯데리아
1076, 삼척 : 강원 삼척시 진주로32
1077, 수원권선 : 경기 수원시 권선구 동수원로 242번길 20
1078, 양주덕정 : 경기 양주시 고암길 306-77
1079, 시흥은행 : 경기 시흥시 대은로83
1080, 대전송촌 : 대전 대덕구 동춘당로 94번길 11-7
1081, 공주신관 : 충남 공주시 흑수골길 34
1082, 군산나운 : 전북 군산시 하나운로 73
1083, 광주오치 : 광주 광역시 북구 오치동 949-27
1084, 울산범서 : 울산 울주군 범서읍 천상길 29
1085, 일산마두 : 경기 고양시 일산동구 일산로 239번길
1086, 평택안중 : 경기 평택시 안중읍 안중로 109-2
1087, 해남 : 전남 해남군 해남읍 중앙2로 해남읍 중앙2로 22
1088, 고성 : 경남 고성군 고성읍 동외로 178번길 3-19
1089, 까치산역 : 까치산역3번출구에서 50미터
1090, 대전송강 : 대전 유성구 구즉로 71
1091, 김해진영 : 경남 김해시 진영읍 여래로 18
1092, 강원대학 : 강원 춘천시 서부대성로 243
1093, 구미동아 : 경북 구미시 송원동로 28
1094, 청주사천 : 충북 청주시 상당구 사뜸로 49
1095, 경산사동 : 경북 경산시 원효로32길 23
1096, 대구신당 : 대구 달서구 계대동문로 24-1
1097, 북비산 : 대구 서구 달서로 182
1098, 창원대학 : 경남 창원시 의창구 퇴촌로 31-1
1099, 신림녹두 : 서울 관악구 신림로23길 16
1100, 일동 : 경기 포천시 일동면 화동로 1051번길 4-7
1101, 충주칠금 : 충북 충주시 칠금12길 5
1102, 안산한양대 : 경기 안산시 상록구 광덕1로 379
1103, 진천 : 충북 진천군 진천읍 중앙동로 56
1104, 홈플러스거제 : 경남 거제시 장평로 12 홈플러스지하1층
1105, 구로가산 : 서울 금천구 디지털로 188
1106, 청주분평 : 충북 청주시 흥덕구 월평로 4
1107, 창원대방 : 경남 창원시 성산구 가양로124번길 13
1108, 대전노은 : 대전 유성구 은구비로42
1109, 안산D/T : 경기 안산시 상록구 예술광장1로 68
1110, 대전갈마 : 대전 서구 갈마로64
1111, 경주황성 : 경북 경주시 황성로 33
1112, 성환 : 충남 천안시 서북구성환읍 성환2로 372-1
1113, 포항양덕 : 경북 포항시 북구 천마로 68
1114, 월드점 : 잠실 키자니아 맞은편
1115, 광주운남 : 광주 광산구 하남대로 282
1116, 인천남동구청 : 인천 남동구 장승남로 54
1117, 청주사창 : 충북 청주시 흥덕구 내수동로116(사창동)
1118, 아차산역 : 서울 광진구 천호대로 665
1119, 광양중동 : 전남 광양시 공영로62(중동)
1120, 울산터미널 : 울산 남구 화합로 133
1121, 태안 : 충남 태안군 태안읍 동백로 291-4
1122, 탑마트신다대 : 부산 사하구 다송로 58
1123, 인천연수 : 인천 연수구 샘말로 55
1124, 계룡 : 충남 계룡시 엄사면 엄사리 번영로 36번지
1125, 동수원 : 경기 수원시 팔달구 인계로 166번길 48-21
1126, 진주상대 : 경남 진주시 동진로175
1127, 대구화원 : 대구 달성군 화원읍 비슬로 2566-1
1128, 시흥정왕 : 경기 시흥시 정왕대로 220
1129, 청주율량 : 충북 청주시 청원구 율봉로 197 102.103호(율량동875-6)
1130, 거제옥포 : 경남 거제시 옥포로 177
1131, 여천 : 전남 여수시 시청로 43 (학동)
1132, 춘천명동EXP : 강원 춘천시 중앙로1가 91
1133, 경안제일 : 경기 광주시 중앙로 152
1134, 쌍문역 : 서울 도봉구 도봉로 484
1135, 광주일곡 : 광주 북구 설죽로 506-3  (일곡동)
1136, 순천금당 : 전남 순천시 조례못등길25(조례동)
1137, GS마트상계 : 서울 노원구 한글비석로 471
1138, 신부여 : 충남 부여군 부여읍 사비로 86
1139, 부천고강 : 경기 부천시 오정구 역곡로481번길 9
1140, 전곡 : 경기 연천군 전곡읍 온골로 49
1141, 안양 : 경기 안양시 만안구 안양로 292번길 28
1142, 마석 : 경기 남양주시화도읍 마석로 14
1143, 나주 : 전남 나주시 나주로 186
1144, 철원동송 : 강원 철원군 동송읍 이평1리 679-2
1145, 부산반여 : 부산 해운대구 재반로 209
1146, 대구평리 : 대구 서구 국채보상로 246
1147, 목동사거리 : 서울 양천구 등촌로 28
1148, 전주효자CGV : 전북 전주시 완산구 용머리로 46
1149, 서산터미날 : 충남 서산시 안견로 190
1150, 대구북부터미날 : 대구 서구 서대구로 295-6
1151, 사천 : 경남 사천시 정동면 옥산로 46번지 청솔빌딩 1층
1152, 인천부개 : 인천 부평구 길주남로 155
1153, 신평탑마트 : 부산 사하구 하신중앙로 210
1154, 세이브마트 : 서울 관악구 난곡로 220
1155, 옥천 : 충북 옥천군 옥천읍 중앙로 45
1156, 남해 : 경남 남해군 남해읍 화전로 52-1
1157, 대구용산 : 대구 달서구 평리로 50
1158, 인천옥련 : 인천 연수구 둑배로 40번길 39
1159, 광주봉선 : 광주 남구 봉선 중앙로82(봉선동)
1160, 부산대신 : 부산 서구 구덕로 340번길 4
1161, 청주개신 : 충북 청주시 흥덕구 경신로 31-1
1162, 천안백석 : 천안시 서북구 백석동 861 웰빙라이프103,104호
1163, 주안고려 : 인천 남구 주안동 미추홀대로 743
1164, 청주용암 : 충북 청주시 상당구 월평로 172
1165, 광주염주 : 광주 서구 월드컵4강로 66(화정동)
1166, 연신내역 : 서울 은평구 연서로 227
1167, 인천구월 : 모래내시장 입구,롯데캐슬 정문 맞은편
1168, 금산 : 충남 금산군 금산읍 인삼로 71(앤이씨티 101호)
1169, 인천병방 : 인천 계양구 장제로 907
1170, 홍천 : 강원 홍천군 홍천읍 신장대리 79-71
1171, 여주 : 경기 여주시 세종로 21
1172, 마천 : 서울 송파구 마천로 315
1173, 영대병원 : 대구 남구 대명로 313
1174, 전주서신 : 전북 전주시 완산구 당산로 112  (서신동)
1175, 포항오천 : 경북 포항시 남구 오천읍 정몽주로 675
1176, 충북영동 : 충북 영동군 영동읍 중앙로 22-1
1177, 신탄진 : 대전시 대덕구 신탄진로818-1
1178, 인천계양 : 인천 계양구 용종로 2 계산프라자 1층
1179, 노원역 : 서울 노원구 상계로 64
1180, 증평 : 충북 증평군 증평읍 중앙로 215-1
1181, 강변씨네마 : 서울 광진구 광나루로 56길 85
1182, 점촌 : 경북 문경시 호서로 2
1183, 구포 : 부산 북구 낙동대로 1698
1184, 금호 : 서울 성동구 장터길 23
1185, 강변테크노 : 서울 광진구 광나루로 56길 85 지하1층
1186, 영도남항 : 남항동 농협 사거리에 위치.
1187, 팔달시장 : 대구 북구 팔달로 145
1188, 면목중앙 : 서울 중랑구 면목로 415
1189, 대전타임월드 : 대전 서구 둔지로 17(둔산동)
1190, 평택중앙 : 경기 평택시 평택2로 10번길 10-3
1191, 부산장림 : 부산 사하구 장평로 145번길 77
1192, 김해어방 : 경남 김해시 인제로 190
1193, 북마산 : 경남 창원시 마산회원구 북성로 118
1194, 광주충장 : 광주 동구 충장로 77-7
1195, 인천신기 : 인천 남구 인하로 287
1196, 제주시청 : 제주 제주시 중앙로 246-1
1197, 포천 : 경기 포천시 신읍동 41-3번지
1198, 김제 : 전북 김제시 화동길 6
1199, 순천연향 : 순천연향동 동부 상설시장 옆
1200, 경북왜관 : 경북 칠곡군 왜관읍 중앙로 212
1201, 수원화서 : 경기 수원시 팔달구 팔달로 105
1202, 대구대곡 : 대구 달서구 도원로 30
1203, 영도동삼 : 부산 영도구 동삼로 25
1204, 원주우산 : 강원 원주시 우산로 72
1205, 구서 : 부산 금정구 구서로 3-1
1206, 창원용호 : 경남 창원시 의창구 용지로153번길 7
1207, 구로시장 : 서울 구로구 구로6동 141-5
1208, 홍성 : 충남 홍성군 홍성읍 아문길29번길82
1209, 하양 : 경북 경산시 하양읍 하양로 126
1210, 대구계명 : 대구 남구 현충로 250
1211, 구미인동 : 경북 구미시 인동중앙로 36-10
1212, 영천시장 : 경북 영천시 완산로 완산로 73
1213, 대전도마 : 대전 서구 계백로 1435
1214, 대전은행 : 대전시 중구 중앙로 174(은행동)
1215, 문현 : 부산 남구 수영로 15
1216, 광주터미널 : 광주 서구 무진대로 904
1217, 용인터미널 : 경기 용인시 처인구 중부대로 1486
1218, 구미형곡 : 경북 구미시 형곡동로 54
1219, 대전중동 : 대전시 동구 중앙로 189-1(중동)
1220, 동두천 : 경기 동두천시 중앙로 270
1221, 거창 : 경남 거창군 거창읍 아림로 20-1
1222, 통영 : 경남 통영시 중앙로 111
1223, 인천백운 : 인천 부평구 경원대로1240번길
1224, 하남덕풍 : 경기 하남시 신장로 147
1225, 언양 : 울산 울주군 언양읍 읍성로 27
1226, 신제주 : 제주 제주시 연북로 22, 101호
1227, 덕천 : 부산 북구 덕천 1길 26
1228, 제물포 : 인천 남구 경인로 124
1229, 산본중앙 : 경기 군포시 산본로 343번길 21
1230, 대구복현 : 대구 북구 검단로 8
1231, 대구지산 : 대구 수성구 지범로 203
1232, 대구효목 : 대구 수성구 화랑로 116
1233, 양주리치마트 : 경기 양주시 덕계동 평화로1415
1234, 예산 : 충남 예산군 예산읍 예산로194번길 13-2
1235, 울산대학 : 울산 남구 대학로 90-1
1236, 논산 : 논산 터미널 옆에 위치 해있습니다
1237, 남원 : 전북 남원시 남문로 448
1238, 부천원미 : 경기 부천시 원미구 부천로 53
1239, 대구봉덕 : 대구 남구 봉덕로 90-1
1240, 부천원종 : 부천시 오정구 원종동 280-13
1241, 정읍 : 전북 정읍시 조곡천 1길 55(수성동)
1242, 롯데부산본점시네마 : 부산 부산진구 가야대로 772
1243, 부산비프광장 : 부산 중구 구덕로 58-1
1244, 신갈 : 경기 용인시 기흥구 신갈로 60
1245, 강릉터미날 : 강원 강릉시 하슬라로 15
1246, 보은 : 충북 보은군 보은읍 보은로 95
1247, 김해부원 : 경남 김해시 가락로 13
1248, 화곡시장 : 서울 강서구 가로공원로 76길 56 (화곡동) 1층
1249, 상주 : 경북 상주시 중앙로 185
1250, 대구만촌 : 대구 수성구 청호로 498
1251, 부산용호 : 부산 남구 용호로 136-1
1252, 양산 : 경남 양산시 삼일로 91
1253, 대천 : 충남 보령시 번영로 41(대천동)
1254, 동대구 : 대구 동구 동부로 30길 7(신세계백화점 맞은편)
1255, 금촌 : 금촌역 일방통행길
1256, 여수중앙 : 전남 여수시 통제영3길12
1257, 공주 : 충남 공주시 웅진로 150
1258, 대구신암 : 대구 동구 신암로 102-1
1259, 군산 : 전북 군산시 대학로 52
1260, 안산선부 : 경기 안산시 단원구 달미로 63
1261, 대구감삼 : 대구 서구 달구벌대로 1669
1262, 대구상인 : 대구 달서구 상인서로 107
1263, 안산상록수 : 경기 안산시 상록구 상록수로40
1264, 둔산선사 : 대전광역시 서구 청사서로 42 효성프라자 1층
1265, 부천송내 : 경기 부천시 원미구 부일로 202-13
1266, 마산창동 : 경남 창원시 마산합포구 창동거리길 28-1
1267, 속초 : 강원도 속초시 금호동 중앙로 128
1268, 부산진역 : 부산 동구 중앙대로 377
1269, 성대시장 : 서울시 동작구 동작구 상도3동 324-1 (지하철7호선 신대방삼거리역 1번출구)
1270, 서귀포 : 제주 서귀포시 중정로61번길 9(서귀포)
1271, 경산 : 경북 경산시 중앙로 83
1272, 응암 : 서울 은평구 은평로 136
1273, 석계 : 서울 노원구 화랑로 325
1274, 온양 : 충남 아산시 온궁로 32
1275, 성남신흥 : 경기 성남시 수정구 산성대로 241번길 239
1276, 부산연산 : 부산 연제구 반송로8
1277, 인천계산 : 인천 계양구 경명대로 1049(계산동)
1278, 순천 : 전남 순천시 중앙 6길 14
1279, 수원매탄 : 경기 수원시 영통구 중부대로 248
1280, 구로디지털역 : 서울 관악구 시흥대로 578
1281, 대전동부 : 대전 동구 동서대로1695번길 30
1282, 영주 : 경북 영주시 번영로 156
1283, 대전버드내 : 대전 중구 태평로 30
1284, 구미 : 경북 구미시 구미중앙로 100
1285, 부산양정 : 부산 부산진구 양정1동 중앙대로 901-1
1286, 불광 : 서울 은평구 통일로 741
1287, 광주금남로 : 광주 광역시 동구 서석로51
1288, 충주 : 충북 충주시 예성로151
1289, 제천 : 제천시 중앙로1가 119번지
1290, 원당 : 경기 고양시 덕양구 마상로 154번길 68 (성사동)
1291, 춘천명동 : 강원 춘천시 조양동 125
1292, 길동 : 서울 강동구 천호대로 1124
1293, 포항 : 경북 포항시 북구 중앙로 282
1294, 마들역 : 서울 노원구 동일로 1528
1295, 언더랜드 : 서울 송파구 올림픽로 240
1296, 서울랜드점 : 경기 과천시 막계동 광명로 181(서울랜드)
1297, 소공2호 : 서울 중구 남대문로 81

1298, 동서울터미널 : 서울 광진구 구의3동546-1
1299, 봉천 : 서울 관악구 관악로212
1300, 강릉 : 강원 강릉시 경강로 2106
1301, 원주일산 : 강원 원주시 천사로 213
1302, 성남 : 경기 성남시 수정구 수정로 181
1303, 대전중앙 : 대전광역시 중구 선화동 3-3번지
1304, 홈서비스과천 : 경기 과천시 별양동 19-4
1305, 홈서비스부암(부산역) : 부산 부산진구 부암동 722-3번지

In [9]:
# URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [10]:
# store_names, store_addrs 길이 확인
len(store_names), len(store_addrs)

(1306, 1306)

In [11]:
# 수집된 정보로 DataFrame 생성
dat = {'지점명':store_names, '주소':store_addrs}
dat = pd.DataFrame(dat)
dat.head()

        지점명                    주소
0  가평휴게소(상)   경기 가평군 설악면 미사리로 544
1      아산장재     서울 용산구 한강대로71길 47
2      수원파장     경기 수원시 장안구 파장로 91
3    롯데더몰여수        전남 여수시 국포1로 36
4      김포마산  경기 김포시 김포한강8로148번길 5

In [12]:
# 수집된 데이터 전처리 전 저장
dat.to_excel('lotteria_all_store_v1.xlsx', index=False)
dat.to_csv('lotteria_all_store_v1.csv', index=False)
dat.head()

        지점명                    주소
0  가평휴게소(상)   경기 가평군 설악면 미사리로 544
1      아산장재     서울 용산구 한강대로71길 47
2      수원파장     경기 수원시 장안구 파장로 91
3    롯데더몰여수        전남 여수시 국포1로 36
4      김포마산  경기 김포시 김포한강8로148번길 5

In [13]:
# 수집된 데이터 가져오기
dat = pd.read_excel('./lotteria_all_store_v1.xlsx')
dat

              지점명                                     주소
0        가평휴게소(상)                    경기 가평군 설악면 미사리로 544
1            아산장재                      서울 용산구 한강대로71길 47
2            수원파장                      경기 수원시 장안구 파장로 91
3          롯데더몰여수                         전남 여수시 국포1로 36
4            김포마산                   경기 김포시 김포한강8로148번길 5
5          신정네거리역                         서울 양천구 신월로 297
6         대구성당D/T                         대구 달서구 구마로 209
7            진주혁신                          경남 진주시 소호로 12
8            영암대불                   전남 영암군 삼호읍 대불주거로 145
9            안산사동                     경기 안산시 상록구 항가울로 28
10          의정부고산                        경기 의정부시 문충로 116
11       용인휴게소(하)            경기 용인시 처인구 양지면 주북로94번길 30-1
12       진영휴게소(하)                경남 김해시 진영읍 하계로94번길 94-4
13          포항에비뉴                       경북 포항시 남구 중흥로 77
14         송도달빛공원    인천 연수구 송도동 29-1번지(아트센터대로 169번길 100)
15           광명역사                 경기 광명시 광명역로 광명역 동편 맞이방
16           문경시청                          경북 문경시 시청1길 5
17         청계산입구역                        서울 서초구 청계산로 201
18          대전목원대                       대전 서구 도안북로93번길 7
19           원주봉산                          강원 원주시 행구로 69
20             무안                    전남 무안군 무안읍 면성1길 129
21       안산그랑시티자이  경기 안산시 상록구 해양1로 199, 그랑시티 PORT AVENUE
22          시화거북섬                         경기 시흥시 거북섬5길 4
23          인천왕길역                           인천 서구 봉화로 49
24         홈플러스강동                     굽은다리역 앞 홈플러스강동점 1층
25           서천장항                      충남 서천군 장항읍 장서로 73
26         경기북부청사                        경기 의정부시 장곡로 620
27       송도랜드마크시티                        인천 연수구 랜드마크로 68
28           청주동남            충북 청주시 상당구 중고개로 141번길 13-16
29          남양주덕소                    경기 남양주시 와부읍 수레로 100
...           ...                                    ...
1276         부산연산                            부산 연제구 반송로8
1277         인천계산                  인천 계양구 경명대로 1049(계산동)
1278           순천                        전남 순천시 중앙 6길 14
1279         수원매탄                    경기 수원시 영통구 중부대로 248
1280       구로디지털역                        서울 관악구 시흥대로 578
1281         대전동부                    대전 동구 동서대로1695번길 30
1282           영주                         경북 영주시 번영로 156
1283        대전버드내                           대전 중구 태평로 30
1284           구미                       경북 구미시 구미중앙로 100
1285         부산양정                부산 부산진구 양정1동 중앙대로 901-1
1286           불광                         서울 은평구 통일로 741
1287        광주금남로                        광주 광역시 동구 서석로51
1288           충주                          충북 충주시 예성로151
1289           제천                        제천시 중앙로1가 119번지
1290           원당          경기 고양시 덕양구 마상로 154번길 68 (성사동)
1291         춘천명동                         강원 춘천시 조양동 125
1292           길동                       서울 강동구 천호대로 1124
1293           포항                      경북 포항시 북구 중앙로 282
1294          마들역                        서울 노원구 동일로 1528
1295         언더랜드                        서울 송파구 올림픽로 240
1296        서울랜드점               경기 과천시 막계동 광명로 181(서울랜드)
1297         소공2호                          서울 중구 남대문로 81
1298       동서울터미널                       서울 광진구 구의3동546-1
1299           봉천                          서울 관악구 관악로212
1300           강릉                        강원 강릉시 경강로 2106
1301         원주일산                         강원 원주시 천사로 213
1302           성남                     경기 성남시 수정구 수정로 181
1303         대전중앙                     대전광역시 중구 선화동 3-3번지
1304       홈서비스과천                        경기 과천시 별양동 19-4
1305  홈서비스부암(부산역)                    부산 부산진구 부암동 722-3번지

[1306 rows x 2 columns]

In [14]:
# 주소를 행정구역으로 나눔
dat[['주소1', '주소2', '주소3']] = pd.DataFrame(dat['주소'].str.split(' ', 2).tolist())
dat.head()

        지점명                    주소 주소1  주소2            주소3
0  가평휴게소(상)   경기 가평군 설악면 미사리로 544  경기  가평군   설악면 미사리로 544
1      아산장재     서울 용산구 한강대로71길 47  서울  용산구     한강대로71길 47
2      수원파장     경기 수원시 장안구 파장로 91  경기  수원시     장안구 파장로 91
3    롯데더몰여수        전남 여수시 국포1로 36  전남  여수시        국포1로 36
4      김포마산  경기 김포시 김포한강8로148번길 5  경기  김포시  김포한강8로148번길 5

In [15]:
# 주소1에 이상치를 확인
dat['주소1'].unique()

array(['경기', '서울', '전남', '대구', '경남', '경북', '인천', '대전', '강원', '굽은다리역',
       '충남', '충북', '감일백제로', '세종', '광주', '부산', '제주', '울산', '전북', '경기도',
       '충청북도', '경상남도', '전라북도', '진안군', '인천공항', '동대문구', '부산광역시', '경남남도',
       '문경새재도립공원', '번동사거리', '서울특별시', '대전시', '롯데마트', '동해시', '중곡동', '대전광역시',
       '지하철', '강남역', '방학', '광혜원시외버스정류장', '성수역1번출구', '서울시', '도화', '용인시',
       '홈배달', '수완지구', '별곡리', '부산시', '잠실', '백마역', '2호선', '청량리역3번출구',
       '충청남도', '회룡역', '진건초등학교', '두정역에서', '죽곡', '주례역', '야탑역4번출구', '창원시',
       '대우자동차', '동암남로', '광주광역시', '화성시', '단계동', '까치산역3번출구에서', '천안시',
       '모래내시장', '남항동', '순천연향동', '논산', '부천시', '금촌역', '강원도', '제천시'],
      dtype=object)

In [16]:
# 주소1의 줄임말을 풀어서 치환
addr = {'서울시':'서울특별시',
        '서울':'서울특별시',
        '부산시':'부산광역시',
        '부산':'부산광역시',
        '대구':'대구광역시',
        '인천':'인천광역시',
        '광주':'광주광역시',
        '대전시':'대전광역시',
        '대전':'대전광역시',
        '울산':'울산광역시',
        '세종':'세종특별자치시',
        '경기':'경기도',
        '강원':'강원도',
        '충북':'충청북도',
        '충남':'충청남도',
        '전북':'전라북도',
        '전남':'전라남도',
        '경북':'경상북도',
        '경남':'경상남도',
        '제주':'제주특별자치도'}

dat['주소1'] = dat['주소1'].replace(addr)

dat['주소1'].unique()

array(['경기도', '서울특별시', '전라남도', '대구광역시', '경상남도', '경상북도', '인천광역시', '대전광역시',
       '강원도', '굽은다리역', '충청남도', '충청북도', '감일백제로', '세종특별자치시', '광주광역시',
       '부산광역시', '제주특별자치도', '울산광역시', '전라북도', '진안군', '인천공항', '동대문구', '경남남도',
       '문경새재도립공원', '번동사거리', '롯데마트', '동해시', '중곡동', '지하철', '강남역', '방학',
       '광혜원시외버스정류장', '성수역1번출구', '도화', '용인시', '홈배달', '수완지구', '별곡리', '잠실',
       '백마역', '2호선', '청량리역3번출구', '회룡역', '진건초등학교', '두정역에서', '죽곡', '주례역',
       '야탑역4번출구', '창원시', '대우자동차', '동암남로', '화성시', '단계동', '까치산역3번출구에서',
       '천안시', '모래내시장', '남항동', '순천연향동', '논산', '부천시', '금촌역', '제천시'],
      dtype=object)

In [17]:

# 210702 롯데리아 강남역 이슈
# 네이버지도에 롯데리아 강남역 검색결과 없어서 주소 확인
# 주소 : 강남역 9번이나 10번출구 뉴욕제과 뒷건물
# 뉴욕제과 확인 :         로드뷰 확인결과 2012년 03월까지 있었지만 현재는 없음
# 롯데리아 강남역점 확인 : 로드뷰 확인 결과 2017년 5월까지 있었지만 이후 없어지고 KFC 생김

# 210703 롯데리아 주안D/T 이슈
# 네이버지도에 위치가 확인이 안됨
# 네이버 블로그에 있는 지도로 위치 확인
# 로드뷰 확인결과 2019년 05월까지 있었지만 현재는 없음
   
# 주소1의 이상값을 정상값으로 변경하고 없는 지점은 None처리
def change_addr(x) :
    
    s_name_ori = x['지점명']
    
    # D/T 같이 '/'이 포함된 경우 네이버에 제대로 검색되지 않음
    s_name = s_name_ori
    if '/' in s_name :
        s_name = s_name.replace('/', '')
        
    f_name = f'롯데리아 {s_name}'
    
    url = f'https://search.naver.com/search.naver?query={f_name}'
          
    driver.get(url)
    time.sleep(1)
    
    page = driver.page_source
    soup = BeautifulSoup(page, 'lxml')
    
    # 네이버에 '롯데리아 지점명' 검색하여 주소 획득
    try :

        # case1 : 롯데리아 감일
        full_addr = soup.select_one('span.addr').text
        addr1, addr2, addr3 = full_addr.split(' ', 2)
        print(f'{s_name} : {addr1} {addr2} {addr3}')
        x[ ['주소1', '주소2', '주소3'] ] = addr1, addr2, addr3

    except Exception as e :

        print(f'{s_name} : 1. {e}')
        full_addr = ''

        try :
            store_list = soup.select('div._3ZU00')
            
            # case2 : 롯데리아 의정부화룡역
            if len(store_list) == 0 :
                full_addr = soup.select('div._1mAZf')[1].text

                full_addr = full_addr[:full_addr.rindex('지번')]
                addr1, addr2, addr3 = full_addr.split(' ', 2)
                print(f'{s_name} : {addr1} {addr2} {addr3}')
                x[ ['주소1', '주소2', '주소3'] ] = addr1, addr2, addr3

            # 검색목록이 여러개인 경우, 지점명과 일치하는 주소를 획득
            for idx, i in enumerate(store_list) :
                
                except_text = ['전북', '전남', '경북', '경남']
                
                # try 구문을 사용해도 되지만 이미 이중으로 try 선언이 되어 굳이 String으로 해결
                # 지점명에 도명이 포함된 경우, 네이버 검색 시 도명이 없이 롯데리아 진안점으로 검색됨
                # 도명을 제거하여 네이버 검색결과 중 일치하는 지점의 주소를 입력
                s_name2 = 'None 선언시 에러가 생기므로 String으로 None 선언'
                if s_name[:2] in except_text :
                    s_name2 = s_name[2:]

                # case3 : 롯데리아 전북진안, 롯데리아 강남역
                if s_name in i.a.text or s_name2 in i.a.text :
                
                    try :
                        xpath = f'//*[@id="loc-main-section-root"]/section/div/div[2]/ul/li[{idx+1}]/div[2]/div[2]/div/span/a/span[2]'
                        down = driver.find_element_by_xpath(xpath)
                    except :
                        # case4 : 롯데리아 경남함안
                        xpath = f'//*[@id="loc-main-section-root"]/section/div/div[2]/ul/li[{idx+1}]/div[1]/div[2]/div/span/a/span[2]'
                        down = driver.find_element_by_xpath(xpath)

                    down.click()
                    time.sleep(1)
                    
                    # 주소에 도로명과, 복사를 뺴고 입력
                    full_addr = driver.find_element_by_css_selector('div._2b9ic').text[3:-2]
                    addr1, addr2, addr3 = full_addr.strip().split(' ', 2)
                    print(f'{s_name} : {addr1} {addr2} {addr3}')
                    x[ ['주소1', '주소2', '주소3'] ] = addr1, addr2, addr3
                    
                    break
                    
        except Exception as e:

            print(f'{s_name} : 2. {e}')
            
    if len(full_addr) < 1 :
        # drop 처리하려 했으나 작업 편의성을 위해 None 처리
#         print(f'{s_name_ori} : 삭제')
#         dat.drop( dat.loc[ dat['지점명'] == s_name_ori ].index, axis=0, inplace=True)

        print(f'{s_name_ori} : None처리')
        pass
    else :
        return x

# 웹드라이버 실행
driver = webdriver.Chrome('../chromedriver_90')

# 주소1의 이상값을 정상값으로 변경하고 없는 지점은 None처리
dat = dat.apply(lambda x : change_addr(x) if x['주소1'] not in addr.values() else x, axis=1)

# 웹드라이버 종료
driver.close()

홈플러스강동 : 서울 강동구 양재대로 1571
감일 : 경기 하남시 감일백제로 109
전북진안 : 1. 'NoneType' object has no attribute 'text'
전북진안 : 전라북도 진안군 진안읍 진무로 1093 1층 롯데리아
인천공항제2여객터미널1층 : 인천 중구 제2터미널대로 446
장한평역 : 1. 'NoneType' object has no attribute 'text'
장한평역 : 서울특별시 동대문구 천호대로 401
외대역 : 1. 'NoneType' object has no attribute 'text'
외대역 : 서울특별시 동대문구 휘경로 5-1
경남함안 : 1. 'NoneType' object has no attribute 'text'
경남함안 : 경상남도 함안군 가야읍 함마대로 1514-25
문경새재 : 경북 문경시 문경읍 새재로 928
번동DT : 서울 강북구 한천로 963
롯데마트수원천천 : 경기 수원시 장안구 만석로19번길 25-10
동해쇄운 : 강원 동해시 청운1길 52
중곡 : 1. 'NoneType' object has no attribute 'text'
중곡 : 서울특별시 광진구 면목로 136 창원빌딩
부산미남역 : 부산 동래구 아시아드대로 234
강남역 : 1. 'NoneType' object has no attribute 'text'
강남역 : None처리
방학 : 1. 'NoneType' object has no attribute 'text'
방학 : 서울특별시 도봉구 방학로 173
광혜원 : 충북 진천군 광혜원면 장기길 104
성수역 : 1. 'NoneType' object has no attribute 'text'
성수역 : 서울특별시 성동구 아차산로7길 28 성수쇼핑센타
주안DT : 1. 'NoneType' object has no attribute 'text'
주안DT : 2. list index out of range
주안D/T : None처리
용인죽전1동 : 1. 'NoneType' object has no attribute 'text'
용인죽전1동 : 경기도 용인시 수지구 현암로 154
수원정자 : 1. 'NoneType' object has no attribute 'text'
수원정자 : 경기도 수원시 장안구 정자천로173번길 17 107호
광주수완 : 1. 'NoneType' object has no attribute 'text'
광주수완 : 광주광역시 광산구 임방울대로 338
단양 : 1. 'NoneType' object has no attribute 'text'
단양 : 충청북도 단양군 단양읍 삼봉로 315
키자니아 : 1. 'NoneType' object has no attribute 'text'
키자니아 : 서울특별시 송파구 올림픽로 240 2층
일산풍동 : 1. 'NoneType' object has no attribute 'text'
일산풍동 : 경기도 고양시 일산동구 숲속마을로 48
신림역 : 1. 'NoneType' object has no attribute 'text'
신림역 : 서울특별시 관악구 남부순환로 1610
청량리 : 1. 'NoneType' object has no attribute 'text'
청량리 : 서울특별시 동대문구 왕산로 209
의정부회룡역 : 1. 'NoneType' object has no attribute 'text'
의정부회룡역 : 경기도 의정부시 평화로 374 한승아파트
진건 : 1. 'NoneType' object has no attribute 'text'
진건 : 경기도 남양주시 진건읍 진건오남로 75 롯데리아
천안두정 : 1. 'NoneType' object has no attribute 'text'
천안두정 : 충청남도 천안시 서북구 봉정로 380 혜성빌딩
대구다사 : 1. 'NoneType' object has no attribute 'text'
대구다사 : 대구광역시 달성군 다사읍 달구벌대로 874 A동 107호
부산주례역 : 부산 사상구 가야대로 316
야탑역 : 경기 성남시 분당구 성남대로925번길 11
창원팔용 : 1. 'NoneType' object has no attribute 'text'
창원팔용 : 경상남도 창원시 의창구 사화로80번길 1
인천청천 : 인천 부평구 마장로 396
동암남부 : 인천 부평구 동암남로 5
화성남양 : 경기 화성시 남양읍 남양성지로 147
원주하나로 : 강원 원주시 무실로 182
까치산역 : 1. 'NoneType' object has no attribute 'text'
까치산역 : 서울특별시 강서구 강서로 35 롯데리아
월드점 : 1. 'NoneType' object has no attribute 'text'
월드점 : 서울특별시 송파구 올림픽로 240 1층 롯데월드 스포츠센타
천안백석 : 충남 천안시 서북구 백석4길 4
인천구월 : 1. 'NoneType' object has no attribute 'text'
인천구월 : 인천광역시 남동구 구월로 270
영도남항 : 부산 영도구 영선대로 83
순천연향 : 1. 'NoneType' object has no attribute 'text'
순천연향 : 전라남도 순천시 연향3로 43 롯데리아
논산 : 1. 'NoneType' object has no attribute 'text'
논산 : 충청남도 논산시 중앙로398번길 13-9 더 채움 리저브 건물 1층
부천원종 : 1. 'NoneType' object has no attribute 'text'
부천원종 : 경기도 부천시 소사로 756
금촌 : 1. 'NoneType' object has no attribute 'text'
금촌 : 경기도 파주시 문화로 105
제천 : 1. 'NoneType' object has no attribute 'text'
제천 : 충청북도 제천시 풍양로13길 5

In [18]:
# null 확인
dat.isnull().sum()

지점명    2
주소     2
주소1    2
주소2    2
주소3    2
dtype: int64

In [19]:
# 주소1의 줄임말을 풀어서 치환하고 None처리 된 행을 제거
dat['주소1'] = dat['주소1'].replace(addr)
dat.dropna(inplace=True)
dat.head()

        지점명                    주소    주소1  주소2            주소3
0  가평휴게소(상)   경기 가평군 설악면 미사리로 544    경기도  가평군   설악면 미사리로 544
1      아산장재     서울 용산구 한강대로71길 47  서울특별시  용산구     한강대로71길 47
2      수원파장     경기 수원시 장안구 파장로 91    경기도  수원시     장안구 파장로 91
3    롯데더몰여수        전남 여수시 국포1로 36   전라남도  여수시        국포1로 36
4      김포마산  경기 김포시 김포한강8로148번길 5    경기도  김포시  김포한강8로148번길 5

In [20]:
# null 확인
dat.isnull().sum()

지점명    0
주소     0
주소1    0
주소2    0
주소3    0
dtype: int64

In [21]:
# 주소1 이상치 확인
dat['주소1'].unique()

array(['경기도', '서울특별시', '전라남도', '대구광역시', '경상남도', '경상북도', '인천광역시', '대전광역시',
       '강원도', '충청남도', '충청북도', '세종특별자치시', '광주광역시', '부산광역시', '제주특별자치도',
       '울산광역시', '전라북도'], dtype=object)

In [22]:
# 주소1, 주소2, 주소3 을 합쳐서 주소를 다시 입력
dat['주소'] = dat[ ['주소1', '주소2', '주소3'] ].apply(' '.join, axis=1)
dat.head()

        지점명                     주소    주소1  주소2            주소3
0  가평휴게소(상)   경기도 가평군 설악면 미사리로 544    경기도  가평군   설악면 미사리로 544
1      아산장재   서울특별시 용산구 한강대로71길 47  서울특별시  용산구     한강대로71길 47
2      수원파장     경기도 수원시 장안구 파장로 91    경기도  수원시     장안구 파장로 91
3    롯데더몰여수       전라남도 여수시 국포1로 36   전라남도  여수시        국포1로 36
4      김포마산  경기도 김포시 김포한강8로148번길 5    경기도  김포시  김포한강8로148번길 5

In [23]:
# 수집된 데이터 전처리 전 저장
dat.to_excel('lotteria_all_store_v2.xlsx', index=False)
dat.to_csv('lotteria_all_store_v2.csv', index=False)
dat.head()

        지점명                     주소    주소1  주소2            주소3
0  가평휴게소(상)   경기도 가평군 설악면 미사리로 544    경기도  가평군   설악면 미사리로 544
1      아산장재   서울특별시 용산구 한강대로71길 47  서울특별시  용산구     한강대로71길 47
2      수원파장     경기도 수원시 장안구 파장로 91    경기도  수원시     장안구 파장로 91
3    롯데더몰여수       전라남도 여수시 국포1로 36   전라남도  여수시        국포1로 36
4      김포마산  경기도 김포시 김포한강8로148번길 5    경기도  김포시  김포한강8로148번길 5

In [88]:
# 수집된 데이터 가져오기
dat = pd.read_excel('./lotteria_all_store_v2.xlsx')
dat

,지점명,주소,주소1,주소2,주소3
0,가평휴게소(상),경기도 가평군 설악면 미사리로 544,경기도,가평군,설악면 미사리로 544
1,아산장재,서울특별시 용산구 한강대로71길 47,서울특별시,용산구,한강대로71길 47
2,수원파장,경기도 수원시 장안구 파장로 91,경기도,수원시,장안구 파장로 91
3,롯데더몰여수,전라남도 여수시 국포1로 36,전라남도,여수시,국포1로 36
4,김포마산,경기도 김포시 김포한강8로148번길 5,경기도,김포시,김포한강8로148번길 5
5,신정네거리역,서울특별시 양천구 신월로 297,서울특별시,양천구,신월로 297
6,대구성당D/T,대구광역시 달서구 구마로 209,대구광역시,달서구,구마로 209
7,진주혁신,경상남도 진주시 소호로 12,경상남도,진주시,소호로 12
8,영암대불,전라남도 영암군 삼호읍 대불주거로 145,전라남도,영암군,삼호읍 대불주거로 145
9,안산사동,경기도 안산시 상록구 항가울로 28,경기도,안산시,상록구 항가울로 28
10,의정부고산,경기도 의정부시 문충로 116,경기도,의정부시,문충로 116
11,용인휴게소(하),경기도 용인시 처인구 양지면 주북로94번길 30-1,경기도,용인시,처인구 양지면 주북로94번길 30-1
12,진영휴게소(하),경상남도 김해시 진영읍 하계로94번길 94-4,경상남도,김해시,진영읍 하계로94번길 94-4
13,포항에비뉴,경상북도 포항시 남구 중흥로 77,경상북도,포항시,남구 중흥로 77
14,송도달빛공원,인천광역시 연수구 송도동 29-1번지(아트센터대로 169번길 100),인천광역시,연수구,송도동 29-1번지(아트센터대로 169번길 100)
15,광명역사,경기도 광명시 광명역로 광명역 동편 맞이방,경기도,광명시,광명역로 광명역 동편 맞이방
16,문경시청,경상북도 문경시 시청1길 5,경상북도,문경시,시청1길 5
17,청계산입구역,서울특별시 서초구 청계산로 201,서울특별시,서초구,청계산로 201
18,대전목원대,대전광역시 서구 도안북로93번길 7,대전광역시,서구,도안북로93번길 7
19,원주봉산,강원도 원주시 행구로 69,강원도,원주시,행구로 69
20,무안,전라남도 무안군 무안읍 면성1길 129,전라남도,무안군,무안읍 면성1길 129
21,안산그랑시티자이,"경기도 안산시 상록구 해양1로 199, 그랑시티 PORT AVENUE",경기도,안산시,"상록구 해양1로 199, 그랑시티 PORT AVENUE"
22,시화거북섬,경기도 시흥시 거북섬5길 4,경기도,시흥시,거북섬5길 4
23,인천왕길역,인천광역시 서구 봉화로 49,인천광역시,서구,봉화로 49
24,홈플러스강동,서울특별시 강동구 양재대로 1571,서울특별시,강동구,양재대로 1571
25,서천장항,충청남도 서천군 장항읍 장서로 73,충청남도,서천군,장항읍 장서로 73
26,경기북부청사,경기도 의정부시 장곡로 620,경기도,의정부시,장곡로 620
27,송도랜드마크시티,인천광역시 연수구 랜드마크로 68,인천광역시,연수구,랜드마크로 68
28,청주동남,충청북도 청주시 상당구 중고개로 141번길 13-16,충청북도,청주시,상당구 중고개로 141번길 13-16
29,남양주덕소,경기도 남양주시 와부읍 수레로 100,경기도,남양주시,와부읍 수레로 100
...,...,...,...,...,...
1274,부산연산,부산광역시 연제구 반송로8,부산광역시,연제구,반송로8
1275,인천계산,인천광역시 계양구 경명대로 1049(계산동),인천광역시,계양구,경명대로 1049(계산동)
1276,순천,전라남도 순천시 중앙 6길 14,전라남도,순천시,중앙 6길 14
1277,수원매탄,경기도 수원시 영통구 중부대로 248,경기도,수원시,영통구 중부대로 248
1278,구로디지털역,서울특별시 관악구 시흥대로 578,서울특별시,관악구,시흥대로 578
1279,대전동부,대전광역시 동구 동서대로1695번길 30,대전광역시,동구,동서대로1695번길 30
1280,영주,경상북도 영주시 번영로 156,경상북도,영주시,번영로 156
1281,대전버드내,대전광역시 중구 태평로 30,대전광역시,중구,태평로 30
1282,구미,경상북도 구미시 구미중앙로 100,경상북도,구미시,구미중앙로 100
1283,부산양정,부산광역시 부산진구 양정1동 중앙대로 901-1,부산광역시,부산진구,양정1동 중앙대로 901-1
1284,불광,서울특별시 은평구 통일로 741,서울특별시,은평구,통일로 741
1285,광주금남로,광주광역시 광역시 동구 서석로51,광주광역시,광역시,동구 서석로51
1286,충주,충청북도 충주시 예성로151,충청북도,충주시,예성로151
1287,제천,충청북도 제천시 풍양로13길 5,충청북도,제천시,풍양로13길 5
1288,원당,경기도 고양시 덕양구 마상로 154번길 68 (성사동),경기도,고양시,덕양구 마상로 154번길 68 (성사동)
1289,춘천명동,강원도 춘천시 조양동 125,강원도,춘천시,조양동 125
1290,길동,서울특별시 강동구 천호대로 1124,서울특별시,강동구,천호대로 1124
1291,포항,경상북도 포항시 북구 중앙로 282,경상북도,포항시,북구 중앙로 282
1292,마들역,서울특별시 노원구 동일로 1528,서울특별시,노원구,동일로 1528
1293,언더랜드,서울특별시 송파구 올림픽로 240,서울특별시,송파구,올림픽로 240
1294,서울랜드점,경기도 과천시 막계동 광명로 181(서울랜드),경기도,과천시,막계동 광명로 181(서울랜드)
1295,소공2호,서울특별시 중구 남대문로 81,서울특별시,중구,남대문로 81
1296,동서울터미널,서울특별시 광진구 구의3동546-1,서울특별시,광진구,구의3동546-1
1297,봉천,서울특별시 관악구 관악로212,서울특별시,관악구,관악로212
1298,강릉,강원도 강릉시 경강로 2106,강원도,강릉시,경강로 2106
1299,원주일산,강원도 원주시 천사로 213,강원도,원주시,천사로 213
1300,성남,경기도 성남시 수정구 수정로 181,경기도,성남시,수정구 수정로 181
1301,대전중앙,대전광역시 중구 선화동 3-3번지,대전광역시,중구,선화동 3-3번지
1302,홈서비스과천,경기도 과천시 별양동 19-4,경기도,과천시,별양동 19-4
1303,홈서비스부암(부산역),부산광역시 부산진구 부암동 722-3번지,부산광역시,부산진구,부암동 722-3번지

## 이상치, 결측치 처리

In [89]:
dat["주소2"].isna().sum()

6

### 1. nan 값 처리
- 세종특별자치시는 행정구가 없기 때문에 주소2에 세종시 입력
- 세종특별자치시는 1읍 9면 10행정동 18법정동으로 구성

In [90]:
dat[dat["주소1"] == "세종특별자치시"]

,지점명,주소,주소1,주소2,주소3
37,세종반곡,세종특별자치시 한누리대로 1824,세종특별자치시,NaN,한누리대로 1824
79,세종고운,세종특별자치시 마음안1로 137,세종특별자치시,NaN,마음안1로 137
80,세종보람디엠시티,세종특별자치시 한누리대로 2165,세종특별자치시,NaN,한누리대로 2165
83,세종소담,세종특별자치시 한누리대로 2009,세종특별자치시,NaN,한누리대로 2009
289,세종종촌,세종특별자치시 도움1로 108,세종특별자치시,NaN,도움1로 108
313,세종부강,세종특별자치시 부강면 부강로 42,세종특별자치시,NaN,부강면 부강로 42
373,세종첫마을,세종특별자치시 연기면 나성길 세종특별자치시 나성동 540번지,세종특별자치시,연기면,나성길 세종특별자치시 나성동 540번지
375,홈플러스세종,세종특별자치시 금남면 세종로 세종특별자치시 어진동 307-3,세종특별자치시,금남면,세종로 세종특별자치시 어진동 307-3
842,홈플러스조치원,세종특별자치시 조치원읍 허만석로 60-1,세종특별자치시,조치원읍,허만석로 60-1
891,조치원,세종특별자치시 조치원읍 조치원로 27-1,세종특별자치시,조치원읍,조치원로 27-1

In [91]:
dat.loc[dat["주소1"] == '세종특별자치시', '주소2'] = '세종특별자치시'
dat[dat["주소1"] == "세종특별자치시"]

,지점명,주소,주소1,주소2,주소3
37,세종반곡,세종특별자치시 한누리대로 1824,세종특별자치시,세종특별자치시,한누리대로 1824
79,세종고운,세종특별자치시 마음안1로 137,세종특별자치시,세종특별자치시,마음안1로 137
80,세종보람디엠시티,세종특별자치시 한누리대로 2165,세종특별자치시,세종특별자치시,한누리대로 2165
83,세종소담,세종특별자치시 한누리대로 2009,세종특별자치시,세종특별자치시,한누리대로 2009
289,세종종촌,세종특별자치시 도움1로 108,세종특별자치시,세종특별자치시,도움1로 108
313,세종부강,세종특별자치시 부강면 부강로 42,세종특별자치시,세종특별자치시,부강면 부강로 42
373,세종첫마을,세종특별자치시 연기면 나성길 세종특별자치시 나성동 540번지,세종특별자치시,세종특별자치시,나성길 세종특별자치시 나성동 540번지
375,홈플러스세종,세종특별자치시 금남면 세종로 세종특별자치시 어진동 307-3,세종특별자치시,세종특별자치시,세종로 세종특별자치시 어진동 307-3
842,홈플러스조치원,세종특별자치시 조치원읍 허만석로 60-1,세종특별자치시,세종특별자치시,허만석로 60-1
891,조치원,세종특별자치시 조치원읍 조치원로 27-1,세종특별자치시,세종특별자치시,조치원로 27-1

In [92]:
dat.loc[dat["지점명"] == '세종첫마을', '주소3'] = '나성동 540번지'
dat.loc[dat["지점명"] == '홈플러스세종', '주소3'] = '어진동 307-3'
dat[dat["주소1"] == "세종특별자치시"]

          지점명                                 주소      주소1      주소2         주소3
37       세종반곡                세종특별자치시  한누리대로 1824  세종특별자치시  세종특별자치시  한누리대로 1824
79       세종고운                 세종특별자치시  마음안1로 137  세종특별자치시  세종특별자치시   마음안1로 137
80   세종보람디엠시티                세종특별자치시  한누리대로 2165  세종특별자치시  세종특별자치시  한누리대로 2165
83       세종소담                세종특별자치시  한누리대로 2009  세종특별자치시  세종특별자치시  한누리대로 2009
289      세종종촌                  세종특별자치시  도움1로 108  세종특별자치시  세종특별자치시    도움1로 108
313      세종부강                세종특별자치시  부강면 부강로 42  세종특별자치시  세종특별자치시  부강면 부강로 42
373     세종첫마을  세종특별자치시 연기면 나성길 세종특별자치시 나성동 540번지  세종특별자치시  세종특별자치시   나성동 540번지
375    홈플러스세종  세종특별자치시 금남면 세종로 세종특별자치시 어진동 307-3  세종특별자치시  세종특별자치시   어진동 307-3
842   홈플러스조치원             세종특별자치시 조치원읍 허만석로 60-1  세종특별자치시  세종특별자치시   허만석로 60-1
891       조치원             세종특별자치시 조치원읍 조치원로 27-1  세종특별자치시  세종특별자치시   조치원로 27-1

### 2. 주소2 데이터 값이 이상한 경우
1. 군+읍/면가 합쳐서 나온 경우 (예) 나주시금천면
    - 분리시켜주기
2. 시,군,구,읍,면 등과 같은 행정구역 단위로 끝나지 않는 경우 (예) 구리, 종로2가
    - 값을 직접 지정해주기

In [93]:
dat["주소2"].unique()

array(['가평군', '용산구', '수원시', '여수시', '김포시', '양천구', '달서구', '진주시', '영암군',
       '안산시', '의정부시', '용인시', '김해시', '포항시', '연수구', '광명시', '문경시', '서초구',
       '서구', '원주시', '무안군', '시흥시', '강동구', '서천군', '청주시', '남양주시', '화성시',
       '하남시', '동구', '마포구', '고양시', '논산시', '세종특별자치시', '천안시', '남구', '사하구',
       '구미시', '북구', '충주시', '안양시', '광주시', '부평구', '평택시', '양양군', '제주시',
       '홍천군', '전주시', '이천시', '은평구', '강서구', '거제시', '산청군', '군포시', '서대문구',
       '달성군', '중구', '수성구', '창원시', '진도군', '남동구', '평창군', '당진시', '성남시',
       '의령군', '익산시', '제천시', '동래구', '부천시', '광산구', '진안군', '안성시', '경산시',
       '노원구', '서산시', '서귀포시', '파주시', '밀양시', '성동구', '금정구', '순천시', '안동시',
       '의성군', '곡성군', '해운대구', '강남구', '부산진구', '영주시', '음성군', '춘천시', '금천구',
       '수영구', '구리시', '관악구', '동대문구', '장수군', '경주시', '보성군', '울릉군', '속초시',
       '인제군', '양주시', '울주군', '송파구', '영등포구', '유성구', '옹진군', '아산시', '오산시',
       '양산시', '중랑구', '정읍시', '의왕시', '동작구', '고성군', '함평군', '김천시', '홍성군',
       '보령시', '무주군', '구례군', '청원군', '강북구', '당진군', '구로구', '강릉시', '여주군',
       '기장군', '나주시금천면', '장성군장성읍', '사상구', '봉화군', '하동군', '성북구', '양평군',
       '고령군', '연제구', '고흥군고흥읍', '순창군', '논산시연무읍', '임실군임실읍', '창녕군남지읍', '광진구',
       '영천시', '완주군', '담양군', '함안군', '부안군', '성주군', '화천군', '강진군', '부여군',
       '장흥군', '군산시', '대덕구', '도봉구', '계양구', '여주시', '동두천시', '목포시', '진구',
       '남원시', '정선군', '종로구', '동해시', '철원군', '괴산군', '포천시', '영광군', '청양군',
       '광양시', '진천군', '아산신', '완도군', '단양군', '함양군', '통영시', '을주군', '화순군',
       '광역시', '태백시', '영덕군', '칠곡군', '고창군', '영월군', '청도군', '횡성군', '예천군',
       '옥천군', '양구군', '합천군', '종로2가', '과천시', '창녕군', '구로', '사천시', '강화군',
       '울진군', '삼척시', '공주시', '해남군', '태안군', '계룡시', '연천군', '남양주시화도읍', '나주시',
       '남해군', '금산군', '영동군', '증평군', '영도구', '김제시', '거창군', '예산군', '보은군',
       '상주시'], dtype=object)

In [94]:
# 주소2의 이름이 시,군,구,동으로 끝나지 않거나 길이가 긴 경우 exc에 저장

exc = []
for one in dat["주소2"].unique():
    try :
        if len(one)>5:
            if one == '세종특별자치시' :
                pass
            else :
                exc.append(one)
        elif one[-1] not in ['시','구','군','동','면',"읍"] :
            exc.append(one)
    except :
        print(one)

exc

['나주시금천면',
 '장성군장성읍',
 '고흥군고흥읍',
 '논산시연무읍',
 '임실군임실읍',
 '창녕군남지읍',
 '아산신',
 '종로2가',
 '구로',
 '남양주시화도읍']

In [95]:
si = ['시','구','군']
idx_list = []

In [96]:
for i in exc :
    
    idx_list.append(dat.loc[dat['주소2'] == i].index[0])
    
    if len(i)>5:
        idx = 0
        
        for j in si :
            try :
                idx = int(i.index(j))
            except :
                pass
        
        addr3 = i[idx+1:] + ' ' + dat.loc[dat['주소2'] == i, '주소3'].values[0]

        dat.loc[dat['주소2'] == i, '주소3'] = addr3
        dat.loc[dat['주소2'] == i, '주소2'] = i[:idx+1]
        
    elif i == "구로":
        dat.loc[dat['주소2'] == i, '주소2'] = '구로구'
    elif i == "종로2가":
        dat.loc[dat['주소2'] == i, '주소2'] = '종로구'
    elif i == "아산신":
        dat.loc[dat['주소2'] == i, '주소2'] = '아산시'

In [97]:
dat.iloc[idx_list]

       지점명                      주소    주소1   주소2             주소3
366   나주혁신  전라남도 나주시금천면 빛가람로 189-1   전라남도   나주시  금천면 빛가람로 189-1
368   전남장성     전라남도 장성군장성읍 영천로 166   전라남도   장성군     장성읍 영천로 166
404   전남고흥     전라남도 고흥군고흥읍 여산당촌길 8   전라남도   고흥군     고흥읍 여산당촌길 8
418   논산연무     충청남도 논산시연무읍 안심로 152   충청남도   논산시     연무읍 안심로 152
427     임실      전라북도 임실군임실읍 운수로 19   전라북도   임실군      임실읍 운수로 19
434   경남남지    경상남도 창녕군남지읍 문화길 35-4   경상남도   창녕군    남지읍 문화길 35-4
678   아산탕정    충청남도 아산신 탕정면 탕정면로 37   충청남도   아산시     탕정면 탕정면로 37
984    종각역        서울특별시 종로2가 종로 68  서울특별시   종로구           종로 68
1040   개봉역  서울특별시 구로 경인로 40길 47 1F  서울특별시   구로구   경인로 40길 47 1F
1140    마석      경기도 남양주시화도읍 마석로 14    경기도  남양주시      화도읍 마석로 14

### 확인

In [98]:
addr = dat["주소2"].unique()
print(addr)

result = True
for one in addr:
    if type(one)==float :
        result = False
        print(one)
    elif one[-1] not in ["시","구","군","동","면","읍"]:
        result = False
        print(one)
    elif len(one)>5:
        if one == '세종특별자치시' :
            pass
        else :
            result =False
        print(one)

if result :
    print("결과 : 이상치가 없습니다.")
else :
    print("결과 : 이상치를 모두 출력하였습니다.")

['가평군' '용산구' '수원시' '여수시' '김포시' '양천구' '달서구' '진주시' '영암군' '안산시' '의정부시' '용인시'
 '김해시' '포항시' '연수구' '광명시' '문경시' '서초구' '서구' '원주시' '무안군' '시흥시' '강동구' '서천군'
 '청주시' '남양주시' '화성시' '하남시' '동구' '마포구' '고양시' '논산시' '세종특별자치시' '천안시' '남구'
 '사하구' '구미시' '북구' '충주시' '안양시' '광주시' '부평구' '평택시' '양양군' '제주시' '홍천군' '전주시'
 '이천시' '은평구' '강서구' '거제시' '산청군' '군포시' '서대문구' '달성군' '중구' '수성구' '창원시' '진도군'
 '남동구' '평창군' '당진시' '성남시' '의령군' '익산시' '제천시' '동래구' '부천시' '광산구' '진안군' '안성시'
 '경산시' '노원구' '서산시' '서귀포시' '파주시' '밀양시' '성동구' '금정구' '순천시' '안동시' '의성군' '곡성군'
 '해운대구' '강남구' '부산진구' '영주시' '음성군' '춘천시' '금천구' '수영구' '구리시' '관악구' '동대문구'
 '장수군' '경주시' '보성군' '울릉군' '속초시' '인제군' '양주시' '울주군' '송파구' '영등포구' '유성구' '옹진군'
 '아산시' '오산시' '양산시' '중랑구' '정읍시' '의왕시' '동작구' '고성군' '함평군' '김천시' '홍성군' '보령시'
 '무주군' '구례군' '청원군' '강북구' '당진군' '구로구' '강릉시' '여주군' '기장군' '나주시' '장성군' '사상구'
 '봉화군' '하동군' '성북구' '양평군' '고령군' '연제구' '고흥군' '순창군' '임실군' '창녕군' '광진구' '영천시'
 '완주군' '담양군' '함안군' '부안군' '성주군' '화천군' '강진군' '부여군' '장흥군' '군산시' '대덕구' '도봉구'
 '계양구' '여주시' '동두천시' '목포시' '진구' '남원시' '정선군' '종로구' '동해시' '철원군' '괴산군' '포천시'
 '영광군' '청양군' '광양시' '진천군' '완도군' '단양군' '함양군' '통영시' '을주군' '화순군' '광역시' '태백시'
 '영덕군' '칠곡군' '고창군' '영월군' '청도군' '횡성군' '예천군' '옥천군' '양구군' '합천군' '과천시' '사천시'
 '강화군' '울진군' '삼척시' '공주시' '해남군' '태안군' '계룡시' '연천군' '남해군' '금산군' '영동군' '증평군'
 '영도구' '김제시' '거창군' '예산군' '보은군' '상주시']
세종특별자치시
결과 : 이상치가 없습니다.

### 3. 잘못된 정보 처리
- 천안은 충청남도인데 충청북도라고 나와있는 데이터가 있다.

In [99]:
temp_idx = dat[(dat["주소1"]=="충청북도")&(dat["주소2"]=="천안시")].index[0]
dat[(dat["주소1"]=="충청북도")&(dat["주소2"]=="천안시")]

         지점명                    주소   주소1  주소2          주소3
506  천안안서D/T  충청북도 천안시 동남구 망향로 190  충청북도  천안시  동남구 망향로 190

In [100]:
dat.iloc[temp_idx,1] = "충청남도 천안시 동남구 망향로 190"
dat.iloc[temp_idx,2] = "충청남도"

dat.iloc[temp_idx]

지점명                 천안안서D/T
주소     충청남도 천안시 동남구 망향로 190
주소1                    충청남도
주소2                     천안시
주소3             동남구 망향로 190
Name: 506, dtype: object

In [102]:
# 전처리 된 데이터 저장
dat.to_excel('lotteria_all_store_v3.xlsx', index=False)
dat.to_csv('lotteria_all_store_v3.csv', index=False)
dat

,지점명,주소,주소1,주소2,주소3
0,가평휴게소(상),경기도 가평군 설악면 미사리로 544,경기도,가평군,설악면 미사리로 544
1,아산장재,서울특별시 용산구 한강대로71길 47,서울특별시,용산구,한강대로71길 47
2,수원파장,경기도 수원시 장안구 파장로 91,경기도,수원시,장안구 파장로 91
3,롯데더몰여수,전라남도 여수시 국포1로 36,전라남도,여수시,국포1로 36
4,김포마산,경기도 김포시 김포한강8로148번길 5,경기도,김포시,김포한강8로148번길 5
5,신정네거리역,서울특별시 양천구 신월로 297,서울특별시,양천구,신월로 297
6,대구성당D/T,대구광역시 달서구 구마로 209,대구광역시,달서구,구마로 209
7,진주혁신,경상남도 진주시 소호로 12,경상남도,진주시,소호로 12
8,영암대불,전라남도 영암군 삼호읍 대불주거로 145,전라남도,영암군,삼호읍 대불주거로 145
9,안산사동,경기도 안산시 상록구 항가울로 28,경기도,안산시,상록구 항가울로 28
10,의정부고산,경기도 의정부시 문충로 116,경기도,의정부시,문충로 116
11,용인휴게소(하),경기도 용인시 처인구 양지면 주북로94번길 30-1,경기도,용인시,처인구 양지면 주북로94번길 30-1
12,진영휴게소(하),경상남도 김해시 진영읍 하계로94번길 94-4,경상남도,김해시,진영읍 하계로94번길 94-4
13,포항에비뉴,경상북도 포항시 남구 중흥로 77,경상북도,포항시,남구 중흥로 77
14,송도달빛공원,인천광역시 연수구 송도동 29-1번지(아트센터대로 169번길 100),인천광역시,연수구,송도동 29-1번지(아트센터대로 169번길 100)
15,광명역사,경기도 광명시 광명역로 광명역 동편 맞이방,경기도,광명시,광명역로 광명역 동편 맞이방
16,문경시청,경상북도 문경시 시청1길 5,경상북도,문경시,시청1길 5
17,청계산입구역,서울특별시 서초구 청계산로 201,서울특별시,서초구,청계산로 201
18,대전목원대,대전광역시 서구 도안북로93번길 7,대전광역시,서구,도안북로93번길 7
19,원주봉산,강원도 원주시 행구로 69,강원도,원주시,행구로 69
20,무안,전라남도 무안군 무안읍 면성1길 129,전라남도,무안군,무안읍 면성1길 129
21,안산그랑시티자이,"경기도 안산시 상록구 해양1로 199, 그랑시티 PORT AVENUE",경기도,안산시,"상록구 해양1로 199, 그랑시티 PORT AVENUE"
22,시화거북섬,경기도 시흥시 거북섬5길 4,경기도,시흥시,거북섬5길 4
23,인천왕길역,인천광역시 서구 봉화로 49,인천광역시,서구,봉화로 49
24,홈플러스강동,서울특별시 강동구 양재대로 1571,서울특별시,강동구,양재대로 1571
25,서천장항,충청남도 서천군 장항읍 장서로 73,충청남도,서천군,장항읍 장서로 73
26,경기북부청사,경기도 의정부시 장곡로 620,경기도,의정부시,장곡로 620
27,송도랜드마크시티,인천광역시 연수구 랜드마크로 68,인천광역시,연수구,랜드마크로 68
28,청주동남,충청북도 청주시 상당구 중고개로 141번길 13-16,충청북도,청주시,상당구 중고개로 141번길 13-16
29,남양주덕소,경기도 남양주시 와부읍 수레로 100,경기도,남양주시,와부읍 수레로 100
...,...,...,...,...,...
1274,부산연산,부산광역시 연제구 반송로8,부산광역시,연제구,반송로8
1275,인천계산,인천광역시 계양구 경명대로 1049(계산동),인천광역시,계양구,경명대로 1049(계산동)
1276,순천,전라남도 순천시 중앙 6길 14,전라남도,순천시,중앙 6길 14
1277,수원매탄,경기도 수원시 영통구 중부대로 248,경기도,수원시,영통구 중부대로 248
1278,구로디지털역,서울특별시 관악구 시흥대로 578,서울특별시,관악구,시흥대로 578
1279,대전동부,대전광역시 동구 동서대로1695번길 30,대전광역시,동구,동서대로1695번길 30
1280,영주,경상북도 영주시 번영로 156,경상북도,영주시,번영로 156
1281,대전버드내,대전광역시 중구 태평로 30,대전광역시,중구,태평로 30
1282,구미,경상북도 구미시 구미중앙로 100,경상북도,구미시,구미중앙로 100
1283,부산양정,부산광역시 부산진구 양정1동 중앙대로 901-1,부산광역시,부산진구,양정1동 중앙대로 901-1
1284,불광,서울특별시 은평구 통일로 741,서울특별시,은평구,통일로 741
1285,광주금남로,광주광역시 광역시 동구 서석로51,광주광역시,광역시,동구 서석로51
1286,충주,충청북도 충주시 예성로151,충청북도,충주시,예성로151
1287,제천,충청북도 제천시 풍양로13길 5,충청북도,제천시,풍양로13길 5
1288,원당,경기도 고양시 덕양구 마상로 154번길 68 (성사동),경기도,고양시,덕양구 마상로 154번길 68 (성사동)
1289,춘천명동,강원도 춘천시 조양동 125,강원도,춘천시,조양동 125
1290,길동,서울특별시 강동구 천호대로 1124,서울특별시,강동구,천호대로 1124
1291,포항,경상북도 포항시 북구 중앙로 282,경상북도,포항시,북구 중앙로 282
1292,마들역,서울특별시 노원구 동일로 1528,서울특별시,노원구,동일로 1528
1293,언더랜드,서울특별시 송파구 올림픽로 240,서울특별시,송파구,올림픽로 240
1294,서울랜드점,경기도 과천시 막계동 광명로 181(서울랜드),경기도,과천시,막계동 광명로 181(서울랜드)
1295,소공2호,서울특별시 중구 남대문로 81,서울특별시,중구,남대문로 81
1296,동서울터미널,서울특별시 광진구 구의3동546-1,서울특별시,광진구,구의3동546-1
1297,봉천,서울특별시 관악구 관악로212,서울특별시,관악구,관악로212
1298,강릉,강원도 강릉시 경강로 2106,강원도,강릉시,경강로 2106
1299,원주일산,강원도 원주시 천사로 213,강원도,원주시,천사로 213
1300,성남,경기도 성남시 수정구 수정로 181,경기도,성남시,수정구 수정로 181
1301,대전중앙,대전광역시 중구 선화동 3-3번지,대전광역시,중구,선화동 3-3번지
1302,홈서비스과천,경기도 과천시 별양동 19-4,경기도,과천시,별양동 19-4
1303,홈서비스부암(부산역),부산광역시 부산진구 부암동 722-3번지,부산광역시,부산진구,부암동 722-3번지

In [190]:
# 수집된 데이터 가져오기
dat = pd.read_excel('./lotteria_all_store_v3.xlsx')
dat

,지점명,주소,주소1,주소2,주소3
0,가평휴게소(상),경기도 가평군 설악면 미사리로 544,경기도,가평군,설악면 미사리로 544
1,아산장재,서울특별시 용산구 한강대로71길 47,서울특별시,용산구,한강대로71길 47
2,수원파장,경기도 수원시 장안구 파장로 91,경기도,수원시,장안구 파장로 91
3,롯데더몰여수,전라남도 여수시 국포1로 36,전라남도,여수시,국포1로 36
4,김포마산,경기도 김포시 김포한강8로148번길 5,경기도,김포시,김포한강8로148번길 5
5,신정네거리역,서울특별시 양천구 신월로 297,서울특별시,양천구,신월로 297
6,대구성당D/T,대구광역시 달서구 구마로 209,대구광역시,달서구,구마로 209
7,진주혁신,경상남도 진주시 소호로 12,경상남도,진주시,소호로 12
8,영암대불,전라남도 영암군 삼호읍 대불주거로 145,전라남도,영암군,삼호읍 대불주거로 145
9,안산사동,경기도 안산시 상록구 항가울로 28,경기도,안산시,상록구 항가울로 28
10,의정부고산,경기도 의정부시 문충로 116,경기도,의정부시,문충로 116
11,용인휴게소(하),경기도 용인시 처인구 양지면 주북로94번길 30-1,경기도,용인시,처인구 양지면 주북로94번길 30-1
12,진영휴게소(하),경상남도 김해시 진영읍 하계로94번길 94-4,경상남도,김해시,진영읍 하계로94번길 94-4
13,포항에비뉴,경상북도 포항시 남구 중흥로 77,경상북도,포항시,남구 중흥로 77
14,송도달빛공원,인천광역시 연수구 송도동 29-1번지(아트센터대로 169번길 100),인천광역시,연수구,송도동 29-1번지(아트센터대로 169번길 100)
15,광명역사,경기도 광명시 광명역로 광명역 동편 맞이방,경기도,광명시,광명역로 광명역 동편 맞이방
16,문경시청,경상북도 문경시 시청1길 5,경상북도,문경시,시청1길 5
17,청계산입구역,서울특별시 서초구 청계산로 201,서울특별시,서초구,청계산로 201
18,대전목원대,대전광역시 서구 도안북로93번길 7,대전광역시,서구,도안북로93번길 7
19,원주봉산,강원도 원주시 행구로 69,강원도,원주시,행구로 69
20,무안,전라남도 무안군 무안읍 면성1길 129,전라남도,무안군,무안읍 면성1길 129
21,안산그랑시티자이,"경기도 안산시 상록구 해양1로 199, 그랑시티 PORT AVENUE",경기도,안산시,"상록구 해양1로 199, 그랑시티 PORT AVENUE"
22,시화거북섬,경기도 시흥시 거북섬5길 4,경기도,시흥시,거북섬5길 4
23,인천왕길역,인천광역시 서구 봉화로 49,인천광역시,서구,봉화로 49
24,홈플러스강동,서울특별시 강동구 양재대로 1571,서울특별시,강동구,양재대로 1571
25,서천장항,충청남도 서천군 장항읍 장서로 73,충청남도,서천군,장항읍 장서로 73
26,경기북부청사,경기도 의정부시 장곡로 620,경기도,의정부시,장곡로 620
27,송도랜드마크시티,인천광역시 연수구 랜드마크로 68,인천광역시,연수구,랜드마크로 68
28,청주동남,충청북도 청주시 상당구 중고개로 141번길 13-16,충청북도,청주시,상당구 중고개로 141번길 13-16
29,남양주덕소,경기도 남양주시 와부읍 수레로 100,경기도,남양주시,와부읍 수레로 100
...,...,...,...,...,...
1274,부산연산,부산광역시 연제구 반송로8,부산광역시,연제구,반송로8
1275,인천계산,인천광역시 계양구 경명대로 1049(계산동),인천광역시,계양구,경명대로 1049(계산동)
1276,순천,전라남도 순천시 중앙 6길 14,전라남도,순천시,중앙 6길 14
1277,수원매탄,경기도 수원시 영통구 중부대로 248,경기도,수원시,영통구 중부대로 248
1278,구로디지털역,서울특별시 관악구 시흥대로 578,서울특별시,관악구,시흥대로 578
1279,대전동부,대전광역시 동구 동서대로1695번길 30,대전광역시,동구,동서대로1695번길 30
1280,영주,경상북도 영주시 번영로 156,경상북도,영주시,번영로 156
1281,대전버드내,대전광역시 중구 태평로 30,대전광역시,중구,태평로 30
1282,구미,경상북도 구미시 구미중앙로 100,경상북도,구미시,구미중앙로 100
1283,부산양정,부산광역시 부산진구 양정1동 중앙대로 901-1,부산광역시,부산진구,양정1동 중앙대로 901-1
1284,불광,서울특별시 은평구 통일로 741,서울특별시,은평구,통일로 741
1285,광주금남로,광주광역시 광역시 동구 서석로51,광주광역시,광역시,동구 서석로51
1286,충주,충청북도 충주시 예성로151,충청북도,충주시,예성로151
1287,제천,충청북도 제천시 풍양로13길 5,충청북도,제천시,풍양로13길 5
1288,원당,경기도 고양시 덕양구 마상로 154번길 68 (성사동),경기도,고양시,덕양구 마상로 154번길 68 (성사동)
1289,춘천명동,강원도 춘천시 조양동 125,강원도,춘천시,조양동 125
1290,길동,서울특별시 강동구 천호대로 1124,서울특별시,강동구,천호대로 1124
1291,포항,경상북도 포항시 북구 중앙로 282,경상북도,포항시,북구 중앙로 282
1292,마들역,서울특별시 노원구 동일로 1528,서울특별시,노원구,동일로 1528
1293,언더랜드,서울특별시 송파구 올림픽로 240,서울특별시,송파구,올림픽로 240
1294,서울랜드점,경기도 과천시 막계동 광명로 181(서울랜드),경기도,과천시,막계동 광명로 181(서울랜드)
1295,소공2호,서울특별시 중구 남대문로 81,서울특별시,중구,남대문로 81
1296,동서울터미널,서울특별시 광진구 구의3동546-1,서울특별시,광진구,구의3동546-1
1297,봉천,서울특별시 관악구 관악로212,서울특별시,관악구,관악로212
1298,강릉,강원도 강릉시 경강로 2106,강원도,강릉시,경강로 2106
1299,원주일산,강원도 원주시 천사로 213,강원도,원주시,천사로 213
1300,성남,경기도 성남시 수정구 수정로 181,경기도,성남시,수정구 수정로 181
1301,대전중앙,대전광역시 중구 선화동 3-3번지,대전광역시,중구,선화동 3-3번지
1302,홈서비스과천,경기도 과천시 별양동 19-4,경기도,과천시,별양동 19-4
1303,홈서비스부암(부산역),부산광역시 부산진구 부암동 722-3번지,부산광역시,부산진구,부암동 722-3번지

2021.07.07 12:00 김민수 update
### - 데이터 1개 : ‘경기도 여주군’ → ‘경기도 여주시’로 변경 
  - 여주가남점

In [191]:
dat.loc[ dat['주소2'] == '여주군']

      지점명                     주소  주소1  주소2            주소3
356  여주가남  경기도 여주군 가남면 태평리 110-7  경기도  여주군  가남면 태평리 110-7

In [192]:
dat.loc[ dat['주소2'] == '여주군', '주소2'] = '여주시'

In [193]:
dat.loc[ dat['주소2'] == '여주시']

           지점명                     주소  주소1  주소2            주소3
356       여주가남  경기도 여주군 가남면 태평리 110-7  경기도  여주시  가남면 태평리 110-7
543   여주375아울렛      경기도 여주시 명품1로 22-5  경기도  여주시      명품1로 22-5
1169        여주         경기도 여주시 세종로 21  경기도  여주시         세종로 21

### - ‘인천광역시 남구’ → ‘인천광역시 미추홀구‘로 변경
  - 동일한 지역인데 KFC, 버거킹, 맥도날드는 ‘인천광역시 미추홀구‘로 되어있음
  - 시군구별 인구수,인구밀도 데이터에 ‘인천광역시 미추홀구‘로 되어 있어서 이것으로 통일하면 좋을 듯

In [194]:
dat.loc[ (dat['주소1'] == '인천광역시') & (dat['주소2'] == '남구') ]

           지점명                      주소    주소1 주소2            주소3
117   롯데백인천터미널         인천광역시 남구 연남로 35  인천광역시  남구         연남로 35
142       인천도화        인천광역시 남구 숙골로 100  인천광역시  남구        숙골로 100
298         주안       인천광역시 남구 주안로 지하86  인천광역시  남구       주안로 지하86
310     구월아시아드        인천광역시 남구 인하로 563  인천광역시  남구        인하로 563
315       인천학산       인천광역시 남구 한나루로 389  인천광역시  남구       한나루로 389
557   홈플러스인천숭의         인천광역시 남구 석정로 51  인천광역시  남구         석정로 51
569      인천석바위        인천광역시 남구 경원대로848  인천광역시  남구        경원대로848
776       인천간석         인천광역시 남구 주안로219  인천광역시  남구         주안로219
917     홈플러스인하          인천광역시 남구 소성로 6  인천광역시  남구          소성로 6
1053      인천용현        인천광역시 남구 낙섬중로 42  인천광역시  남구        낙섬중로 42
1069      인천학익       인천광역시 남구 매소홀로 466  인천광역시  남구       매소홀로 466
1161      주안고려  인천광역시 남구 주안동 미추홀대로 743  인천광역시  남구  주안동 미추홀대로 743
1193      인천신기        인천광역시 남구 인하로 287  인천광역시  남구        인하로 287
1226       제물포        인천광역시 남구 경인로 124  인천광역시  남구        경인로 124

In [195]:
dat.loc[ (dat['주소1'] == '인천광역시') & (dat['주소2'] == '남구'), '주소2' ] = '미추홀구'

In [196]:
dat.loc[ (dat['주소1'] == '인천광역시') & (dat['주소2'] == '미추홀구') ]

           지점명                      주소    주소1   주소2            주소3
117   롯데백인천터미널         인천광역시 남구 연남로 35  인천광역시  미추홀구         연남로 35
142       인천도화        인천광역시 남구 숙골로 100  인천광역시  미추홀구        숙골로 100
298         주안       인천광역시 남구 주안로 지하86  인천광역시  미추홀구       주안로 지하86
310     구월아시아드        인천광역시 남구 인하로 563  인천광역시  미추홀구        인하로 563
315       인천학산       인천광역시 남구 한나루로 389  인천광역시  미추홀구       한나루로 389
557   홈플러스인천숭의         인천광역시 남구 석정로 51  인천광역시  미추홀구         석정로 51
569      인천석바위        인천광역시 남구 경원대로848  인천광역시  미추홀구        경원대로848
776       인천간석         인천광역시 남구 주안로219  인천광역시  미추홀구         주안로219
917     홈플러스인하          인천광역시 남구 소성로 6  인천광역시  미추홀구          소성로 6
1053      인천용현        인천광역시 남구 낙섬중로 42  인천광역시  미추홀구        낙섬중로 42
1069      인천학익       인천광역시 남구 매소홀로 466  인천광역시  미추홀구       매소홀로 466
1161      주안고려  인천광역시 남구 주안동 미추홀대로 743  인천광역시  미추홀구  주안동 미추홀대로 743
1193      인천신기        인천광역시 남구 인하로 287  인천광역시  미추홀구        인하로 287
1226       제물포        인천광역시 남구 경인로 124  인천광역시  미추홀구        경인로 124

### - 주소에 “광주광역시 광역시“라고 되어있는 데이터 3개 있음 
  - 광주금남로, 광주동림, 광주오치

In [197]:
idx_list2 = list(dat.loc[ dat['주소2'] == '광역시' ].index)
dat.loc[ dat['주소2'] == '광역시' ]

        지점명                       주소    주소1  주소2            주소3
774    광주동림      광주광역시 광역시 서구 동천동626  광주광역시  광역시      서구 동천동626
1081   광주오치  광주광역시 광역시 북구 오치동 949-27  광주광역시  광역시  북구 오치동 949-27
1285  광주금남로       광주광역시 광역시 동구 서석로51  광주광역시  광역시       동구 서석로51

In [198]:
def change_addr2(x) :
    idx = x['주소3'].index('구') + 1
    
    addr2 = x['주소3'][:idx]
    addr3 = x['주소3'][idx+1:]
    
    x['주소2', '주소3'] = addr2, addr3
    
    return x
    
dat = dat.apply(lambda x : change_addr2(x) if x['주소2'] == '광역시' else x, axis=1)

In [199]:
dat.iloc[ idx_list2 ]

        지점명                       주소    주소1 주소2         주소3
774    광주동림      광주광역시 광역시 서구 동천동626  광주광역시  서구      동천동626
1081   광주오치  광주광역시 광역시 북구 오치동 949-27  광주광역시  북구  오치동 949-27
1285  광주금남로       광주광역시 광역시 동구 서석로51  광주광역시  동구       서석로51

In [200]:
# 주소1, 주소2, 주소3 을 합쳐서 주소를 다시 입력
dat['주소'] = dat[ ['주소1', '주소2', '주소3'] ].apply(' '.join, axis=1)
dat.head()

        지점명                     주소    주소1  주소2            주소3
0  가평휴게소(상)   경기도 가평군 설악면 미사리로 544    경기도  가평군   설악면 미사리로 544
1      아산장재   서울특별시 용산구 한강대로71길 47  서울특별시  용산구     한강대로71길 47
2      수원파장     경기도 수원시 장안구 파장로 91    경기도  수원시     장안구 파장로 91
3    롯데더몰여수       전라남도 여수시 국포1로 36   전라남도  여수시        국포1로 36
4      김포마산  경기도 김포시 김포한강8로148번길 5    경기도  김포시  김포한강8로148번길 5

In [201]:
dat.loc[dat["주소1"] == "세종특별자치시"]

          지점명                          주소      주소1      주소2         주소3
37       세종반곡  세종특별자치시 세종특별자치시 한누리대로 1824  세종특별자치시  세종특별자치시  한누리대로 1824
79       세종고운   세종특별자치시 세종특별자치시 마음안1로 137  세종특별자치시  세종특별자치시   마음안1로 137
80   세종보람디엠시티  세종특별자치시 세종특별자치시 한누리대로 2165  세종특별자치시  세종특별자치시  한누리대로 2165
83       세종소담  세종특별자치시 세종특별자치시 한누리대로 2009  세종특별자치시  세종특별자치시  한누리대로 2009
289      세종종촌    세종특별자치시 세종특별자치시 도움1로 108  세종특별자치시  세종특별자치시    도움1로 108
313      세종부강  세종특별자치시 세종특별자치시 부강면 부강로 42  세종특별자치시  세종특별자치시  부강면 부강로 42
373     세종첫마을   세종특별자치시 세종특별자치시 나성동 540번지  세종특별자치시  세종특별자치시   나성동 540번지
375    홈플러스세종   세종특별자치시 세종특별자치시 어진동 307-3  세종특별자치시  세종특별자치시   어진동 307-3
842   홈플러스조치원   세종특별자치시 세종특별자치시 허만석로 60-1  세종특별자치시  세종특별자치시   허만석로 60-1
891       조치원   세종특별자치시 세종특별자치시 조치원로 27-1  세종특별자치시  세종특별자치시   조치원로 27-1

In [202]:
dat['주소'] = dat.apply(lambda x : x['주소1'] + ' ' + x['주소3'] if x['주소1'] == '세종특별자치시' else x['주소'], axis=1)

In [203]:
dat.loc[dat["주소1"] == "세종특별자치시"]

          지점명                  주소      주소1      주소2         주소3
37       세종반곡  세종특별자치시 한누리대로 1824  세종특별자치시  세종특별자치시  한누리대로 1824
79       세종고운   세종특별자치시 마음안1로 137  세종특별자치시  세종특별자치시   마음안1로 137
80   세종보람디엠시티  세종특별자치시 한누리대로 2165  세종특별자치시  세종특별자치시  한누리대로 2165
83       세종소담  세종특별자치시 한누리대로 2009  세종특별자치시  세종특별자치시  한누리대로 2009
289      세종종촌    세종특별자치시 도움1로 108  세종특별자치시  세종특별자치시    도움1로 108
313      세종부강  세종특별자치시 부강면 부강로 42  세종특별자치시  세종특별자치시  부강면 부강로 42
373     세종첫마을   세종특별자치시 나성동 540번지  세종특별자치시  세종특별자치시   나성동 540번지
375    홈플러스세종   세종특별자치시 어진동 307-3  세종특별자치시  세종특별자치시   어진동 307-3
842   홈플러스조치원   세종특별자치시 허만석로 60-1  세종특별자치시  세종특별자치시   허만석로 60-1
891       조치원   세종특별자치시 조치원로 27-1  세종특별자치시  세종특별자치시   조치원로 27-1

In [204]:
# 전처리 된 데이터 저장
dat.to_excel('lotteria_all_store.xlsx', index=False)
dat.to_csv('lotteria_all_store.csv', index=False)
dat

,지점명,주소,주소1,주소2,주소3
0,가평휴게소(상),경기도 가평군 설악면 미사리로 544,경기도,가평군,설악면 미사리로 544
1,아산장재,서울특별시 용산구 한강대로71길 47,서울특별시,용산구,한강대로71길 47
2,수원파장,경기도 수원시 장안구 파장로 91,경기도,수원시,장안구 파장로 91
3,롯데더몰여수,전라남도 여수시 국포1로 36,전라남도,여수시,국포1로 36
4,김포마산,경기도 김포시 김포한강8로148번길 5,경기도,김포시,김포한강8로148번길 5
5,신정네거리역,서울특별시 양천구 신월로 297,서울특별시,양천구,신월로 297
6,대구성당D/T,대구광역시 달서구 구마로 209,대구광역시,달서구,구마로 209
7,진주혁신,경상남도 진주시 소호로 12,경상남도,진주시,소호로 12
8,영암대불,전라남도 영암군 삼호읍 대불주거로 145,전라남도,영암군,삼호읍 대불주거로 145
9,안산사동,경기도 안산시 상록구 항가울로 28,경기도,안산시,상록구 항가울로 28
10,의정부고산,경기도 의정부시 문충로 116,경기도,의정부시,문충로 116
11,용인휴게소(하),경기도 용인시 처인구 양지면 주북로94번길 30-1,경기도,용인시,처인구 양지면 주북로94번길 30-1
12,진영휴게소(하),경상남도 김해시 진영읍 하계로94번길 94-4,경상남도,김해시,진영읍 하계로94번길 94-4
13,포항에비뉴,경상북도 포항시 남구 중흥로 77,경상북도,포항시,남구 중흥로 77
14,송도달빛공원,인천광역시 연수구 송도동 29-1번지(아트센터대로 169번길 100),인천광역시,연수구,송도동 29-1번지(아트센터대로 169번길 100)
15,광명역사,경기도 광명시 광명역로 광명역 동편 맞이방,경기도,광명시,광명역로 광명역 동편 맞이방
16,문경시청,경상북도 문경시 시청1길 5,경상북도,문경시,시청1길 5
17,청계산입구역,서울특별시 서초구 청계산로 201,서울특별시,서초구,청계산로 201
18,대전목원대,대전광역시 서구 도안북로93번길 7,대전광역시,서구,도안북로93번길 7
19,원주봉산,강원도 원주시 행구로 69,강원도,원주시,행구로 69
20,무안,전라남도 무안군 무안읍 면성1길 129,전라남도,무안군,무안읍 면성1길 129
21,안산그랑시티자이,"경기도 안산시 상록구 해양1로 199, 그랑시티 PORT AVENUE",경기도,안산시,"상록구 해양1로 199, 그랑시티 PORT AVENUE"
22,시화거북섬,경기도 시흥시 거북섬5길 4,경기도,시흥시,거북섬5길 4
23,인천왕길역,인천광역시 서구 봉화로 49,인천광역시,서구,봉화로 49
24,홈플러스강동,서울특별시 강동구 양재대로 1571,서울특별시,강동구,양재대로 1571
25,서천장항,충청남도 서천군 장항읍 장서로 73,충청남도,서천군,장항읍 장서로 73
26,경기북부청사,경기도 의정부시 장곡로 620,경기도,의정부시,장곡로 620
27,송도랜드마크시티,인천광역시 연수구 랜드마크로 68,인천광역시,연수구,랜드마크로 68
28,청주동남,충청북도 청주시 상당구 중고개로 141번길 13-16,충청북도,청주시,상당구 중고개로 141번길 13-16
29,남양주덕소,경기도 남양주시 와부읍 수레로 100,경기도,남양주시,와부읍 수레로 100
...,...,...,...,...,...
1274,부산연산,부산광역시 연제구 반송로8,부산광역시,연제구,반송로8
1275,인천계산,인천광역시 계양구 경명대로 1049(계산동),인천광역시,계양구,경명대로 1049(계산동)
1276,순천,전라남도 순천시 중앙 6길 14,전라남도,순천시,중앙 6길 14
1277,수원매탄,경기도 수원시 영통구 중부대로 248,경기도,수원시,영통구 중부대로 248
1278,구로디지털역,서울특별시 관악구 시흥대로 578,서울특별시,관악구,시흥대로 578
1279,대전동부,대전광역시 동구 동서대로1695번길 30,대전광역시,동구,동서대로1695번길 30
1280,영주,경상북도 영주시 번영로 156,경상북도,영주시,번영로 156
1281,대전버드내,대전광역시 중구 태평로 30,대전광역시,중구,태평로 30
1282,구미,경상북도 구미시 구미중앙로 100,경상북도,구미시,구미중앙로 100
1283,부산양정,부산광역시 부산진구 양정1동 중앙대로 901-1,부산광역시,부산진구,양정1동 중앙대로 901-1
1284,불광,서울특별시 은평구 통일로 741,서울특별시,은평구,통일로 741
1285,광주금남로,광주광역시 동구 서석로51,광주광역시,동구,서석로51
1286,충주,충청북도 충주시 예성로151,충청북도,충주시,예성로151
1287,제천,충청북도 제천시 풍양로13길 5,충청북도,제천시,풍양로13길 5
1288,원당,경기도 고양시 덕양구 마상로 154번길 68 (성사동),경기도,고양시,덕양구 마상로 154번길 68 (성사동)
1289,춘천명동,강원도 춘천시 조양동 125,강원도,춘천시,조양동 125
1290,길동,서울특별시 강동구 천호대로 1124,서울특별시,강동구,천호대로 1124
1291,포항,경상북도 포항시 북구 중앙로 282,경상북도,포항시,북구 중앙로 282
1292,마들역,서울특별시 노원구 동일로 1528,서울특별시,노원구,동일로 1528
1293,언더랜드,서울특별시 송파구 올림픽로 240,서울특별시,송파구,올림픽로 240
1294,서울랜드점,경기도 과천시 막계동 광명로 181(서울랜드),경기도,과천시,막계동 광명로 181(서울랜드)
1295,소공2호,서울특별시 중구 남대문로 81,서울특별시,중구,남대문로 81
1296,동서울터미널,서울특별시 광진구 구의3동546-1,서울특별시,광진구,구의3동546-1
1297,봉천,서울특별시 관악구 관악로212,서울특별시,관악구,관악로212
1298,강릉,강원도 강릉시 경강로 2106,강원도,강릉시,경강로 2106
1299,원주일산,강원도 원주시 천사로 213,강원도,원주시,천사로 213
1300,성남,경기도 성남시 수정구 수정로 181,경기도,성남시,수정구 수정로 181
1301,대전중앙,대전광역시 중구 선화동 3-3번지,대전광역시,중구,선화동 3-3번지
1302,홈서비스과천,경기도 과천시 별양동 19-4,경기도,과천시,별양동 19-4
1303,홈서비스부암(부산역),부산광역시 부산진구 부암동 722-3번지,부산광역시,부산진구,부암동 722-3번지

In [205]:
import os
os.getcwd()

'C:\\Users\\Su\\Documents\\GitHub\\burger-index\\1. web_crawling+preprocessing\\Lotteria'

In [206]:
os.listdir()

['.DS_Store',
 '.ipynb_checkpoints',
 'Lotteria.ipynb',
 'lotteria_all_store.csv',
 'lotteria_all_store.xlsx',
 'lotteria_all_store_v1.csv',
 'lotteria_all_store_v1.xlsx',
 'lotteria_all_store_v2.csv',
 'lotteria_all_store_v2.xlsx',
 'lotteria_all_store_v3.csv',
 'lotteria_all_store_v3.xlsx']

2021.07.07 14:30 김동화 update

In [3]:
# 데이터 불러오기, 기존 데이터 v4으로 저장
dat = pd.read_csv("lotteria_all_store.csv")
dat.to_excel('lotteria_all_store_v4.xlsx', index=False)
dat.to_csv('lotteria_all_store_v4.csv', index=False)
dat

              지점명                      주소    주소1   주소2            주소3
0        가평휴게소(상)    경기도 가평군 설악면 미사리로 544    경기도   가평군   설악면 미사리로 544
1            아산장재    서울특별시 용산구 한강대로71길 47  서울특별시   용산구     한강대로71길 47
2            수원파장      경기도 수원시 장안구 파장로 91    경기도   수원시     장안구 파장로 91
3          롯데더몰여수        전라남도 여수시 국포1로 36   전라남도   여수시        국포1로 36
4            김포마산   경기도 김포시 김포한강8로148번길 5    경기도   김포시  김포한강8로148번길 5
...           ...                     ...    ...   ...            ...
1299         원주일산         강원도 원주시 천사로 213    강원도   원주시        천사로 213
1300           성남     경기도 성남시 수정구 수정로 181    경기도   성남시    수정구 수정로 181
1301         대전중앙      대전광역시 중구 선화동 3-3번지  대전광역시    중구      선화동 3-3번지
1302       홈서비스과천        경기도 과천시 별양동 19-4    경기도   과천시       별양동 19-4
1303  홈서비스부암(부산역)  부산광역시 부산진구 부암동 722-3번지  부산광역시  부산진구    부암동 722-3번지

[1304 rows x 5 columns]

### '충청북도 청원군' 처리 : 청원군은 청주시 소속

In [10]:
idx_cw = dat.loc[dat["주소2"]=='청원군','주소2'].index
dat.loc[dat['주소2']=='청원군','주소2'] = '청주시'
dat.iloc[idx_cw]

        지점명                        주소   주소1  주소2              주소3
324    청주강내    충청북도 청원군 강내면 탑연리 277-2  충청북도  청주시    강내면 탑연리 277-2
694    충북오송    충청북도 청원군 오송읍 오송생명로 194  충청북도  청주시    오송읍 오송생명로 194
832  홈플러스오창  충청북도 청원군 오창읍 중심상업1로 8-11  충청북도  청주시  오창읍 중심상업1로 8-11
900      오창      충청북도 청원군 오창읍 중심상업로 7  충청북도  청주시      오창읍 중심상업로 7

### '충청남도 당진군' 처리 : '충청남도 당진시'으로

In [13]:
idx_dj = dat[dat["주소2"]=='당진군'].index
dat.loc[dat['주소2']=='당진군','주소2'] = '당진시'
dat.iloc[idx_dj]

      지점명                     주소   주소1  주소2           주소3
333  당진신평  충청남도 당진군 신평면 거산리 15-6  충청남도  당진시  신평면 거산리 15-6

### '울산광역시 을주군' 처리 : '울산광역시 울주군'으로

In [17]:
idx_wj = dat[dat["주소2"]=='을주군'].index
dat.loc[dat['주소2']=='을주군','주소2'] = '울주군'
dat.iloc[idx_wj]

      지점명                    주소    주소1  주소2         주소3
759  울산온양  울산광역시 을주군 온양읍 온양로 95  울산광역시  울주군  온양읍 온양로 95

### '부산 진구' 처리 : '부산 진구'로 통일

In [21]:
idx_bs = dat[dat['주소2']=='진구'].index
dat.loc[dat['주소2']=="진구","주소2"] = "부산진구"
dat.iloc[idx_bs]

          지점명                 주소    주소1   주소2       주소3
560  홈플러스부산가야  부산광역시 진구 가야대로 506  부산광역시  부산진구  가야대로 506
685    키즈마트부산  부산광역시 진구 신천대로 241  부산광역시  부산진구  신천대로 241

In [22]:
dat.to_excel('lotteria_all_store.xlsx', index=False)
dat.to_csv('lotteria_all_store.csv', index=False)
dat

              지점명                      주소    주소1   주소2            주소3
0        가평휴게소(상)    경기도 가평군 설악면 미사리로 544    경기도   가평군   설악면 미사리로 544
1            아산장재    서울특별시 용산구 한강대로71길 47  서울특별시   용산구     한강대로71길 47
2            수원파장      경기도 수원시 장안구 파장로 91    경기도   수원시     장안구 파장로 91
3          롯데더몰여수        전라남도 여수시 국포1로 36   전라남도   여수시        국포1로 36
4            김포마산   경기도 김포시 김포한강8로148번길 5    경기도   김포시  김포한강8로148번길 5
...           ...                     ...    ...   ...            ...
1299         원주일산         강원도 원주시 천사로 213    강원도   원주시        천사로 213
1300           성남     경기도 성남시 수정구 수정로 181    경기도   성남시    수정구 수정로 181
1301         대전중앙      대전광역시 중구 선화동 3-3번지  대전광역시    중구      선화동 3-3번지
1302       홈서비스과천        경기도 과천시 별양동 19-4    경기도   과천시       별양동 19-4
1303  홈서비스부암(부산역)  부산광역시 부산진구 부암동 722-3번지  부산광역시  부산진구    부암동 722-3번지

[1304 rows x 5 columns]